-- =============================================================
-- THE CABIN — Supabase Storage bucket for photo uploads.
--
-- Bucket: cabin-photos (PRIVATE — accessed only via signed URLs
-- generated by our service-role server). 1 GB free tier covers
-- the first ~50 charters comfortably.
--
-- Object naming convention enforced by app code:
--   cabin-photos/<cabin_id>/mood-board/<random>.jpg
--   cabin-photos/<cabin_id>/voyage/<random>.jpg
--
-- Idempotent — safe to re-run.
-- =============================================================

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'cabin-photos',
  'cabin-photos',
  false,                       -- private; no anon downloads
  5 * 1024 * 1024,            -- 5 MB max per object (we compress
                              -- client-side first to fit comfortably)
  array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

-- RLS on storage.objects: only the service role can read/write the
-- cabin-photos bucket. Anon/auth users get nothing — all client
-- access goes through our /api/cabin/* endpoints which use signed
-- URLs.

do $$ begin
  drop policy if exists "cabin-photos service only read" on storage.objects;
  drop policy if exists "cabin-photos service only write" on storage.objects;
  drop policy if exists "cabin-photos service only update" on storage.objects;
  drop policy if exists "cabin-photos service only delete" on storage.objects;
end $$;

create policy "cabin-photos service only read"
  on storage.objects for select
  using (bucket_id = 'cabin-photos' and auth.role() = 'service_role');

create policy "cabin-photos service only write"
  on storage.objects for insert
  with check (bucket_id = 'cabin-photos' and auth.role() = 'service_role');

create policy "cabin-photos service only update"
  on storage.objects for update
  using (bucket_id = 'cabin-photos' and auth.role() = 'service_role');

create policy "cabin-photos service only delete"
  on storage.objects for delete
  using (bucket_id = 'cabin-photos' and auth.role() = 'service_role');
