// Bottom-funnel programmatic pages - Phase 7 Round 34 (2026-05-12).
// Technical brief Priority 5A.
//
// 20 high-purchase-intent pages targeting buyers ready to book.
// Each follows the brief-specified structure:
//   - Quick Answer block (Q&A, 60-word answer, George-attributed)
//   - Yacht type / size recommendations (generic descriptors so
//     content stays evergreen without specific vessel names)
//   - Pricing band for this specific segment
//   - Itinerary suggestion (3-5 day skeleton)
//   - 3 reasons to choose George Yachts
//   - FAQ
//
// Schema (per page): TouristTrip + Offer + FAQPage + BreadcrumbList.

export const BOTTOM_FUNNEL_PAGES = [
  {
    slug: "yacht-charter-mykonos-8-guests",
    urlPath: "/yacht-charter-mykonos-8-guests",
    eyebrow: "Mykonos · 8 guests",
    h1: "Yacht Charter in Mykonos for 8 Guests (2026)",
    tagline: "The right yacht size, the right price band, the right anchorages for a party of 8.",
    quickAnswerQ: "What yacht size do I need to charter Mykonos for 8 guests?",
    quickAnswerA: "For 8 guests in Mykonos, target a 30-35m motor yacht (4 cabins, 5-6 crew) or a 38-42 foot luxury catamaran (4 cabins). Peak July-August base rates run €110,000-€165,000 per week for motor yachts at this spec, plus 30% APA, Greek VAT at the certified rate, and 10-15% gratuity. Catamarans run €55,000-€85,000 base.",
    yachtRecs: [
      { kind: "Motor yacht 30-35m", cabins: "4 cabins (1 master + 3 doubles)", crew: "5-6 crew", weekly: "€110,000 - €165,000", fitFor: "Most-requested spec for 8 in Mykonos" },
      { kind: "Sailing yacht 30-35m", cabins: "4 cabins", crew: "4-5 crew", weekly: "€55,000 - €95,000", fitFor: "Lower budget, slower pace" },
      { kind: "Luxury catamaran 38-44ft", cabins: "4 cabins", crew: "3-4 crew", weekly: "€55,000 - €85,000", fitFor: "Stability + shallow draft access" },
    ],
    pricingNote: "Add ~55% to the base for full loaded cost (APA + VAT + delivery + gratuity).",
    itinerary: [
      { day: 1, title: "Embarkation Mykonos · Ornos lunch", body: "Board 17:00. Welcome dinner at anchor in Ornos Bay or Psarou - the captain picks based on Meltemi forecast." },
      { day: 2, title: "Delos morning · Tinos afternoon", body: "Morning archaeology at Delos (UNESCO). Lunch back aboard. Push to Tinos for the food scene + Volax." },
      { day: 3, title: "Naxos + Mikri Vigla", body: "Cruise south. Anchor Mikri Vigla (kitesurfing) or Plaka. Dinner at Tobias Halikiopoulos in Naxos." },
      { day: 4, title: "Schinoussa / Iraklia (Small Cyclades)", body: "Off-grid morning swim. Crystal-clear water, near-empty anchorages." },
      { day: 5, title: "Paros · Naoussa village", body: "Pretty harbour, restaurants (Mario's, Barbarossa). Sunset cocktails aboard." },
      { day: 6, title: "Antiparos channel · Soros", body: "Hidden Cyclades highlight. Soros beach club lunch. Tender to Antiparos town." },
      { day: 7, title: "Return to Mykonos · disembark", body: "Final swim at Ornos or Paranga. Disembark 09:00 Day 8." },
    ],
    whyGeorgeYachts: [
      "Hand-vetted 35m motor yacht inventory matched to your party size and dates.",
      "Real Mykonos-base captains who route around Meltemi without forcing fixed itineraries.",
      "Discreet UHNW handling: George books Nammos and JackieO direct from his contacts list.",
    ],
    faq: [
      { q: "Can 8 guests share an 8-cabin yacht for more space?", a: "Yes - a 40m yacht with 6-8 cabins for 8 guests means everyone has space + privacy. Weekly rate around €200,000-€280,000 base. Often the right call for UHNW couples wanting separation." },
      { q: "Best month for a Mykonos 8-guest charter?", a: "Late June or early September. Same warm water as peak, ~20% lower rate, Meltemi quieter. Mid-July to mid-August is doable but Meltemi can blow 3-5 day stretches." },
      { q: "Can we start from Athens instead of Mykonos?", a: "Yes. Athens (Alimos) is the main Greek base. Saves the delivery fee. Ferry or charter flight to Mykonos for embarkation if dates require Mykonos start." },
    ],
    seoTitle: "Yacht Charter Mykonos for 8 Guests 2026 | Pricing",
    seoDescription: "30-35m motor yacht charter Mykonos for 8 guests. Real pricing (€110k-165k base), itinerary, captain advice. Direct broker contact at George Yachts.",
  },

  {
    slug: "yacht-charter-mykonos-12-guests",
    urlPath: "/yacht-charter-mykonos-12-guests",
    eyebrow: "Mykonos · 12 guests",
    h1: "Yacht Charter in Mykonos for 12 Guests (2026)",
    tagline: "Twelve is the SOLAS overnight cap on any commercial charter. Here's the right yacht for that party size in Mykonos.",
    quickAnswerQ: "What yacht do I need for 12 guests in Mykonos?",
    quickAnswerA: "Twelve guests is the SOLAS overnight cap on any chartered yacht. Target a 40-50m motor yacht (5-6 cabins) or 50-60m superyacht (6+ cabins). Peak July-August base rates: €220,000-€380,000 per week mid-tier, €380,000-€650,000 for upper superyachts. Plus 30% APA, VAT at the certified rate (5.2-6.5% is common at this size), 10-15% gratuity.",
    yachtRecs: [
      { kind: "Motor yacht 40-50m", cabins: "5-6 cabins", crew: "8-10 crew", weekly: "€220,000 - €380,000", fitFor: "Most-balanced 12-guest spec" },
      { kind: "Superyacht 50-60m", cabins: "6+ cabins", crew: "11-14 crew", weekly: "€380,000 - €650,000", fitFor: "Premium service + helipad/spa" },
      { kind: "Luxury catamaran 22-30m", cabins: "5-6 cabins", crew: "6-8 crew", weekly: "€85,000 - €180,000", fitFor: "Stability + value" },
    ],
    pricingNote: "Greek charter VAT at the yacht's certified rate (statutory 13% ceiling). Crew of 10+ means daily gratuity practice converges on 12-13% median.",
    itinerary: [
      { day: 1, title: "Embarkation Mykonos · party night Psarou", body: "Board, Nammos dinner pre-booked. Yacht anchors Psarou overnight." },
      { day: 2, title: "Delos · Rineia", body: "Morning at Delos archaeological site. Lunch + swim at Rineia (the wild island beside Delos)." },
      { day: 3, title: "Naxos · St Anna · Mikri Vigla", body: "Long south-coast Naxos swimming day. Dinner at Tobias Halikiopoulos." },
      { day: 4, title: "Folegandros · Chora village", body: "Chora at dusk - one of the Cyclades' best dinner-and-village evenings." },
      { day: 5, title: "Santorini caldera mooring", body: "Sunset at Ammoudi (mooring buoy pre-booked). Dinner at Sunset Ammoudi." },
      { day: 6, title: "Ios · Manganari Bay", body: "Stunning white-sand crescent. Swim, lunch ashore at Sea Satin." },
      { day: 7, title: "Paros · Naoussa", body: "Final evening Naoussa. Mario's or Barbarossa for dinner." },
    ],
    whyGeorgeYachts: [
      "Specialist in 12-guest superyacht chartering. We've placed >40 SOLAS-cap charters since 2022.",
      "Pre-booked priority access to Mykonos Nammos / JackieO + Delos archaeological tour permits.",
      "Multi-yacht flotilla design for groups of 13+ (we run two yachts in parallel formation).",
    ],
    faq: [
      { q: "Can I exceed 12 guests for a single event aboard?", a: "Yes for day events (lunch, sundowner) - day-guests count separately from overnight guests under SOLAS. The 12-cap is for overnight passengers. Birthday dinners with 18 aboard for one evening are normal." },
      { q: "What if my group is 14-16?", a: "Multi-yacht flotilla: two yachts in parallel formation, shared itinerary, alternating dinner host. Common arrangement for milestone events. Cost ~1.7x a single yacht of equivalent spec." },
      { q: "How early should I book for peak summer?", a: "Top-tier 50m+ for July-August 2026 was 96% committed by mid-May. For 2027 peak, contact George by October 2026." },
    ],
    seoTitle: "Yacht Charter Mykonos for 12 Guests 2026 | SOLAS Rule",
    seoDescription: "40-60m yacht charter Mykonos for 12 guests. Real pricing €220k-650k base. SOLAS rules, multi-yacht options for 13+. Direct broker conversation.",
  },

  {
    slug: "yacht-charter-santorini-couples",
    urlPath: "/yacht-charter-santorini-couples",
    eyebrow: "Santorini · Couples",
    h1: "Santorini Yacht Charter for Couples (2026)",
    tagline: "The Santorini caldera evening from a private yacht is among the Mediterranean's defining moments. Here is how to do it right for a couple.",
    quickAnswerQ: "What's the best yacht charter for a couple in Santorini?",
    quickAnswerA: "For couples, target a 24-32m motor yacht (1-2 cabins, 3-4 crew). Peak July-August base rates: €55,000-€110,000 per week. Highlight: Ammoudi caldera mooring buoy for sunset. The caldera anchorage book 1-2 weeks ahead in peak. Most couples combine 2-3 nights Santorini with 4-5 nights Cyclades.",
    yachtRecs: [
      { kind: "Motor yacht 24-28m", cabins: "1-2 cabins", crew: "3-4 crew", weekly: "€55,000 - €85,000", fitFor: "Intimate, fast, direct caldera access" },
      { kind: "Sailing yacht 30-35m", cabins: "2-3 cabins", crew: "4 crew", weekly: "€55,000 - €95,000", fitFor: "Romantic sailing experience + lower fuel" },
      { kind: "Catamaran 38-44ft", cabins: "2-4 cabins", crew: "2-3 crew", weekly: "€35,000 - €65,000", fitFor: "Maximum stability, intimate spaces" },
    ],
    pricingNote: "Caldera mooring buoy is a real constraint - book through your broker 14+ days ahead in peak.",
    itinerary: [
      { day: 1, title: "Embark Santorini · caldera evening", body: "Board 17:00 Vlychada. Cruise to Ammoudi caldera mooring buoy. Sunset dinner aboard or ashore at Sunset Ammoudi." },
      { day: 2, title: "Thirassia · reverse caldera view", body: "Cross to Thirassia. Lunch at Captain John's taverna. Manolas village walk." },
      { day: 3, title: "Anafi · Roukouna beach", body: "1-night anchorage at the Cyclades' most-isolated inhabited island. Total privacy." },
      { day: 4, title: "Ios · Manganari", body: "White-sand crescent, blue water. Sea Satin lunch ashore." },
      { day: 5, title: "Folegandros · Chora village", body: "Cliff-top village dinner. One of Greece's most-romantic settings." },
      { day: 6, title: "Sikinos · empty bays", body: "Tiny island, two anchorages, near-zero traffic." },
      { day: 7, title: "Return Santorini · disembark Vlychada", body: "Final caldera morning before disembark." },
    ],
    whyGeorgeYachts: [
      "Direct mooring-buoy booking for Ammoudi caldera - we hold relationships with the harbour authority.",
      "Honeymoon-tuned chef pre-briefing (specific menus, champagne service, surprise cake setups).",
      "Captain matching: we know which captains run the romantic schedule vs the activity schedule.",
    ],
    faq: [
      { q: "Should we stay only in Santorini or hop?", a: "Hop. Santorini is best as a 1-2 night anchor moment within a larger Cyclades trip. The caldera evening is the event; the rest of the week happens on the move." },
      { q: "How early should we book the caldera mooring?", a: "14+ days before charter for peak July-August. Less notice = back-up anchorages at Vlychada or south coast (still excellent, less iconic)." },
      { q: "Can the yacht arrange a proposal setup?", a: "Yes. Brief George 21+ days ahead. Flowers, champagne, photographer, custom menu - all routine. Discretion guaranteed." },
    ],
    seoTitle: "Santorini Yacht Charter for Couples 2026 | Itinerary",
    seoDescription: "Yacht charter Santorini for couples - 24-32m motor or sailing yacht. €55k-110k base. Caldera mooring at Ammoudi for sunset. Honeymoon specialist George Yachts.",
  },

  {
    slug: "yacht-charter-greece-under-50000",
    urlPath: "/yacht-charter-greece-under-50000",
    eyebrow: "Under €50k base",
    h1: "Greek Yacht Charter Under €50,000 per Week (2026)",
    tagline: "The honest landscape of Greek charters at the sub-€50k base-rate band. What you get, what you do not, where the value sits.",
    quickAnswerQ: "What can I charter in Greece for under €50,000 per week?",
    quickAnswerA: "Sub-€50k base lands you in the small-to-mid market: 24-30m motor yachts at the entry end, 24-32m sailing yachts, 38-44ft catamarans, or 20-28m gulets. Shoulder-season (June, September) opens 30-35m motor yachts at this price band. Plus 25-30% APA, Greek VAT (est. at the 13% ceiling), 10-15% gratuity. Fully loaded: ~€78,000 at most.",
    yachtRecs: [
      { kind: "Motor yacht 24-30m (mid-tier)", cabins: "3-4 cabins, 4-6 guests", crew: "3-4 crew", weekly: "€30,000 - €50,000", fitFor: "Smaller parties, shoulder season" },
      { kind: "Sailing yacht 28-32m", cabins: "3-4 cabins, 6-8 guests", crew: "3 crew", weekly: "€25,000 - €45,000", fitFor: "Sailing experience + better value/length" },
      { kind: "Luxury catamaran 40-46ft", cabins: "4 cabins, 6-8 guests", crew: "2-3 crew", weekly: "€25,000 - €50,000", fitFor: "Stability, shallow draft, families" },
    ],
    pricingNote: "Add ~55% for full loaded cost. Sub-€50k base = ~€78,000 all-in.",
    itinerary: [
      { day: 1, title: "Embark Athens · Athens Riviera evening", body: "Alimos to Cape Sounion. Sunset dinner aboard with Poseidon Temple view." },
      { day: 2, title: "Kea · Vourkari", body: "Quiet Cyclades intro - Kea is overlooked. Excellent tavernas." },
      { day: 3, title: "Kythnos · Kolona beach", body: "Twin-bay beach formation. Photogenic, near-empty." },
      { day: 4, title: "Serifos · Livadi", body: "Authentic village, donkey path to Chora, fresh fish." },
      { day: 5, title: "Sifnos · pottery and cuisine", body: "Greece's culinary island. Two pottery towns, exceptional tavernas." },
      { day: 6, title: "Milos · Sarakiniko + Kleftiko", body: "Iconic white-volcanic-rock anchorages. Lunch ashore at Pollonia." },
      { day: 7, title: "Return Athens · disembark", body: "Long final passage. Disembark Alimos 09:00 Day 8." },
    ],
    whyGeorgeYachts: [
      "Real inventory in the €25-50k band - we don't push you up-market unnecessarily.",
      "Greek-flagged yachts under MYBA contract for full transparency at every price point.",
      "Athens-based crew network keeps delivery fees minimal on this budget tier.",
    ],
    faq: [
      { q: "What yachts are NOT available under €50k base?", a: "40m+ motor yachts in peak July-August. Performance superyachts. Some headline-name yachts. Most of the rest of the fleet is reachable, especially in June or September." },
      { q: "Can I get a Mykonos / Santorini itinerary under €50k?", a: "Yes in June or September. July-August Mykonos peak rates push the same yachts to €60-90k base." },
      { q: "Does cheaper mean worse?", a: "Not at this band. €30-50k Greek yachts are MYBA-standard with full crew and proper safety equipment. The differences vs €100k+ are amenity depth (smaller spas, fewer water toys, simpler chef briefs), not safety or core service." },
    ],
    seoTitle: "Greek Yacht Charter Under €50,000 a Week 2026",
    seoDescription: "Honest sub-€50k Greek yacht charter market: 24-30m motor, 28-32m sailing, catamarans, gulets. Real pricing, itinerary suggestion. Athens-based.",
  },

  {
    slug: "yacht-charter-greece-under-100000",
    urlPath: "/yacht-charter-greece-under-100000",
    eyebrow: "Under €100k base",
    h1: "Greek Yacht Charter Under €100,000 per Week (2026)",
    tagline: "The mid-luxury band: where the deepest fleet sits and most UHNW family charters land.",
    quickAnswerQ: "What's available under €100,000 per week in Greek charter?",
    quickAnswerA: "Sub-€100k base unlocks 30-38m motor yachts (4-5 cabins, 6-8 crew), 34-42m sailing yachts, premium catamarans 50-65ft, and luxury gulets 32-40m. This is the deepest fleet band in the Greek market - 150+ yachts available. Plus 30% APA, Greek VAT (est. at the 13% ceiling), 10-15% gratuity. Fully loaded ~€155,000 at most.",
    yachtRecs: [
      { kind: "Motor yacht 30-38m", cabins: "4-5 cabins, 8-10 guests", crew: "5-7 crew", weekly: "€65,000 - €100,000", fitFor: "Most-popular UHNW family spec" },
      { kind: "Sailing yacht 34-42m", cabins: "4-5 cabins, 8-10 guests", crew: "4-5 crew", weekly: "€55,000 - €95,000", fitFor: "Sailing experience + larger party" },
      { kind: "Luxury catamaran 50-65ft", cabins: "4-6 cabins", crew: "4-5 crew", weekly: "€55,000 - €100,000", fitFor: "Stability, shallow draft, large deck" },
      { kind: "Luxury gulet 32-40m", cabins: "6-8 cabins, 12 guests", crew: "5-7 crew", weekly: "€45,000 - €95,000", fitFor: "Authentic Mediterranean atmosphere" },
    ],
    pricingNote: "The fleet sweet-spot. Maximum yacht-choice flexibility within budget.",
    itinerary: [
      { day: 1, title: "Embark Mykonos · Ornos", body: "Welcome aboard. Mykonos sunset at anchor in Ornos or Psarou." },
      { day: 2, title: "Delos + Tinos", body: "Morning archaeology. Tinos food evening at Itan Ena Mikro Karavi." },
      { day: 3, title: "Naxos · Mikri Vigla", body: "South-coast Naxos. Family-friendly white-sand swimming." },
      { day: 4, title: "Schinoussa / Iraklia", body: "Empty-anchorage day. Pure Greek-summer reset." },
      { day: 5, title: "Paros + Antiparos channel", body: "Naoussa village evening. Day cruise through the Antiparos channel." },
      { day: 6, title: "Sifnos · culinary day", body: "Lunch + dinner ashore at Greece's food island." },
      { day: 7, title: "Serifos · Kolona · return Athens", body: "Final swim, long passage, disembark Athens Day 8." },
    ],
    whyGeorgeYachts: [
      "150+ yachts to choose from in your exact band - we never propose just 3 options.",
      "Per-yacht captain matching to your party (family / corporate / honeymoon profiles).",
      "Italian wine + French champagne provisioning networks within the chef's APA budget.",
    ],
    faq: [
      { q: "What's the difference vs a €60k charter?", a: "More yacht (4-5 vs 3-4 cabins), more crew, fuller water-toy inventory, often stabilisers, often newer build. The €40k vs €100k step is the largest experiential jump in the Greek charter market." },
      { q: "Can I see actual yacht specs before deciding?", a: "Yes - George shares 4-6 specific yacht shortlists with full deck plans, photos, and current-year price quotes within 48 hours of inquiry." },
      { q: "Is this band still in peak July availability?", a: "Q1 2026 closed ~78% of peak inventory. Mid-tier 30-38m yachts have 22% peak availability remaining as of mid-May 2026." },
    ],
    seoTitle: "Greek Yacht Charter Under €100,000 a Week 2026",
    seoDescription: "Mid-luxury Greek yacht charter: 30-38m motor, 34-42m sailing, catamarans, gulets. 150+ yachts. Real pricing breakdown from George Yachts.",
  },

  {
    slug: "yacht-charter-greece-family-with-children",
    urlPath: "/yacht-charter-greece-family-with-children",
    eyebrow: "Family · Children",
    h1: "Greek Yacht Charter for Families with Children (2026)",
    tagline: "The yachts, anchorages, and crew profiles that actually work for families with kids.",
    quickAnswerQ: "Which yacht works for a family with young children in Greece?",
    quickAnswerA: "Catamarans and 30-40m motor yachts with stabilisers are the family workhorses. Catamarans win on zero roll at anchor (kids sleep through anchor moves) and shallow-draft access to calm beaches. Motor yachts win on space, water-toy inventory, and onboard staff for children's programme. Ionian Sea (no Meltemi) suits younger children; Cyclades for older kids comfortable with summer wind.",
    yachtRecs: [
      { kind: "Power catamaran 26-30m", cabins: "5 cabins", crew: "4-5 crew", weekly: "€75,000 - €130,000", fitFor: "Zero roll, shallow draft, calm beaches" },
      { kind: "Motor yacht 32-40m with stabilisers", cabins: "4-5 cabins", crew: "6-8 crew", weekly: "€140,000 - €240,000", fitFor: "Space, toys, children's programme" },
      { kind: "Sailing catamaran 50-60ft", cabins: "4-6 cabins", crew: "3-4 crew", weekly: "€35,000 - €75,000", fitFor: "Lower budget, family-friendly pace" },
    ],
    pricingNote: "Add age-appropriate water toys to the brief: e-foils (12+), Seabob (10+), towables (all ages).",
    itinerary: [
      { day: 1, title: "Embark Corfu · Kassiopi", body: "Ionian start avoids Meltemi. Family-friendly village evening." },
      { day: 2, title: "Paxos · Lakka", body: "Sheltered, swimming, easy beaches, friendly restaurants." },
      { day: 3, title: "Antipaxos · Voutoumi", body: "Caribbean-clear water. Best children's swimming in Greece." },
      { day: 4, title: "Lefkada · Porto Katsiki", body: "Iconic Ionian beach. Tender access, shallow steps." },
      { day: 5, title: "Kefalonia · Foki / Antisamos", body: "Family-friendly bays + Mamma Mia atmosphere." },
      { day: 6, title: "Ithaca · Vathy", body: "Quaint Odyssean island. Easy village evening." },
      { day: 7, title: "Return Corfu · Agni dining bay", body: "Final lunch at Agni's three world-class tavernas. Disembark Corfu Day 8." },
    ],
    whyGeorgeYachts: [
      "Family-tuned chef briefs: kid menus, allergy management, snack timing across nap windows.",
      "Children's-programme stewardess matching (some yachts have a dedicated kids' steward).",
      "Ionian over Cyclades recommendation when ages are 10 and under - we don't push the Aegean for the photo.",
    ],
    faq: [
      { q: "Cyclades or Ionian for a family with 6-year-old?", a: "Ionian. Wind-stable, calm anchorages, shorter passages, family-tuned tavernas. The Cyclades Meltemi can scare young children and the passages are longer." },
      { q: "Can crew handle infant routines?", a: "Yes - stewardesses are routinely trained for nap timing, bottle prep, baby-monitor support. Brief George 14+ days ahead with specific routines." },
      { q: "What if a child gets seasick?", a: "Stabilisers are the answer. A 32m motor yacht with Seakeeper gyroscopic stabilisers eliminates 95% of roll. Sailing yachts also reduce roll under canvas." },
    ],
    seoTitle: "Greek Yacht Charter for Families with Kids 2026",
    seoDescription: "Yachts, anchorages, crew profiles that work for families with kids. Catamaran vs motor yacht. Ionian vs Cyclades for ages. Family-tested by George Yachts.",
  },

  {
    slug: "yacht-charter-ionian-2-weeks",
    urlPath: "/yacht-charter-ionian-2-weeks",
    eyebrow: "Ionian · 2 weeks",
    h1: "Ionian Yacht Charter for 2 Weeks (2026)",
    tagline: "Fourteen days unlocks the full Ionian: Corfu in the north to Zakynthos in the south, with proper time on each island.",
    quickAnswerQ: "Is 2 weeks enough for a full Ionian yacht charter?",
    quickAnswerA: "Two weeks is the right length for a complete Ionian charter - Corfu, Paxos, Lefkada, Kefalonia, Ithaca, Zakynthos, plus the Diapontia islands. One week is too compressed for the full chain. Pricing scales linearly: 2-week base is ~2x weekly with no discount typically; occasional 5% concession on quieter shoulder dates.",
    yachtRecs: [
      { kind: "Motor yacht 30-40m", cabins: "4-5 cabins", crew: "6-8 crew", weekly: "€110,000 - €240,000", fitFor: "Full Ionian comfort over 14 days" },
      { kind: "Sailing yacht 40-50m", cabins: "4-5 cabins", crew: "5-6 crew", weekly: "€95,000 - €180,000", fitFor: "Sailing experience + Ionian's wind windows" },
      { kind: "Catamaran 45-55ft", cabins: "4-5 cabins", crew: "3-4 crew", weekly: "€35,000 - €75,000", fitFor: "Lower budget, shallow draft" },
    ],
    pricingNote: "Ask about the 7+7 deal: many operators offer a 5-10% concession for 14-night charters in shoulder season.",
    itinerary: [
      { day: 1, title: "Embark Corfu · Kassiopi", body: "Welcome aboard. Northern Corfu evening at Kassiopi village." },
      { day: 2, title: "Diapontia: Erikoussa, Othoni", body: "Day cruise to Corfu's outer islands. Off-grid swimming." },
      { day: 3, title: "Paxos · Lakka", body: "Cross south. Anchor Lakka, dinner at La Rosa di Paxos." },
      { day: 4, title: "Antipaxos · Voutoumi", body: "Caribbean-clear water. Lunch ashore at Bella Vista." },
      { day: 5, title: "Lefkada · Vasiliki + Skorpios anchorage", body: "Sail to Lefkada. Past Onassis's Skorpios island." },
      { day: 6, title: "Lefkada · Porto Katsiki + Egremni", body: "Iconic Ionian beaches. Sunset at Egremni." },
      { day: 7, title: "Meganisi + Kalamos", body: "Quieter islands, fresh fish at Spilia and Kalamos villages." },
      { day: 8, title: "Ithaca · Vathy + Pothia", body: "Odyssean island - village + bay rotation." },
      { day: 9, title: "Kefalonia · Foki + Antisamos", body: "Mamma Mia coast. Anchor at Antisamos for the night." },
      { day: 10, title: "Kefalonia · Myrtos + Assos", body: "Most-photographed Greek beach. Assos village dinner." },
      { day: 11, title: "Zakynthos · Navagio (Shipwreck Beach)", body: "The iconic shot. Anchor outside Navagio cove." },
      { day: 12, title: "Zakynthos · Keri Caves + Marathonisi", body: "Turtle-protection zone. Crystal-clear water." },
      { day: 13, title: "Return Kefalonia + Ithaca", body: "Final island evenings as you slowly head back north." },
      { day: 14, title: "Final Lefkada day + return Corfu", body: "Last anchor at Skorpios or Meganisi before Corfu return." },
    ],
    whyGeorgeYachts: [
      "Deep Ionian routing knowledge: we know which captains can sequence the 6-island chain without backtracking.",
      "Lefkada base partnerships - we can mid-week swap crew or restock at Lefkada marina without itinerary disruption.",
      "Two-week pricing leverage: George negotiates the 5-10% multi-week concession that solo brokers can not.",
    ],
    faq: [
      { q: "Is 2 weeks too much yacht?", a: "Not in the Ionian. With seven distinct islands and three day-cruisable archipelagos, the Ionian fills 14 days without repetition. One week is the compressed version; two weeks is the proper expression." },
      { q: "Can we split: 1 week Ionian, 1 week Cyclades?", a: "Operationally possible but adds delivery time + cost. Most clean: pick one region per charter and return for the other another year." },
      { q: "What about provisioning over 14 days?", a: "Yacht chef re-provisions at Lefkada or Corfu mid-charter. Fresh fish daily from coastal villages. Wines + spirits hold for 14 days on initial APA stock." },
    ],
    seoTitle: "Ionian Yacht Charter for 2 Weeks 2026 | 14-Day Plan",
    seoDescription: "Full Ionian charter, 14 days: Corfu to Zakynthos, Diapontia to Meganisi. Real pricing, sample itinerary, why 2 weeks beats 1. From George Yachts.",
  },

  {
    slug: "yacht-charter-athens-to-mykonos",
    urlPath: "/yacht-charter-athens-to-mykonos",
    eyebrow: "Athens to Mykonos",
    h1: "Yacht Charter Athens to Mykonos (2026)",
    tagline: "Most luxury yachts base in Athens. Embarking Mykonos directly may not be cheaper - here is the honest math.",
    quickAnswerQ: "Is it cheaper to embark yacht charter in Athens vs Mykonos?",
    quickAnswerA: "Usually yes. Most Greek charter yachts base in Athens (Alimos / Olympic Marine). Embarking Mykonos adds a delivery fee of €4,000-€8,000 each way (~1/7 of weekly rate per delivery day). Athens embark saves that, gives you a Sunday/Cape Sounion dinner aboard, then heads to Mykonos by Day 2. Some operators waive delivery for Mykonos start in shoulder season.",
    yachtRecs: [
      { kind: "Motor yacht 30-40m", cabins: "4-5 cabins", crew: "6-8 crew", weekly: "€110,000 - €240,000", fitFor: "Standard Athens-base spec" },
      { kind: "Performance motor yacht 24-32m", cabins: "3-4 cabins", crew: "4-6 crew", weekly: "€65,000 - €165,000", fitFor: "Athens-Mykonos in 4 hours" },
    ],
    pricingNote: "Math: Mykonos embark = base + €8k delivery. Athens embark + Day-2 Mykonos arrival = base + €0 + better first dinner.",
    itinerary: [
      { day: 1, title: "Embark Athens · Cape Sounion", body: "Board Alimos 17:00. Welcome dinner at anchor below the Temple of Poseidon. The proper Greek mythological intro." },
      { day: 2, title: "Kea + Cape Sounion morning · Mykonos arrival", body: "Morning swim at Kea. Push to Mykonos by 17:00. Dinner ashore at Nammos or aboard." },
      { day: 3, title: "Mykonos · Psarou + Delos", body: "Beach club day + Delos archaeology. Sunset back at Ornos." },
      { day: 4, title: "Tinos · food evening", body: "Cross to Tinos. Dinner at Itan Ena Mikro Karavi - Cyclades food destination." },
      { day: 5, title: "Naxos · Mikri Vigla", body: "South-coast white sand. Sea Satin or Manolas for lunch ashore." },
      { day: 6, title: "Paros · Naoussa", body: "Pretty village evening. Mario's restaurant." },
      { day: 7, title: "Antiparos channel · Soros · return Athens", body: "Final Cyclades highlight. Long return passage. Disembark Alimos Day 8 09:00." },
    ],
    whyGeorgeYachts: [
      "Athens-base fleet specialist. We know which yachts can be repositioned for Mykonos embark on which dates without delivery surcharge.",
      "Cape Sounion dinner is our signature opening night - we coordinate with the captain to time anchor for sunset Temple light.",
      "Direct relationships with Alimos / Olympic Marine berthmasters for crew rotation + last-minute embark changes.",
    ],
    faq: [
      { q: "Can I fly into Mykonos and join the yacht there?", a: "Yes. Many charters fly guests to Mykonos on Day 2 to join the yacht. Saves the first night Athens but adds €600-€1,200 charter-flight cost per group." },
      { q: "What about Mykonos return at end of charter?", a: "Operationally possible - we end the charter in Mykonos with a flight back. Same delivery-fee logic: Mykonos disembark adds delivery to return yacht to Athens." },
      { q: "How long is Athens to Mykonos passage?", a: "100 nautical miles. ~5-6 hours at 18-20 knots, 8-10 hours at 12-13 knots. Half a charter day." },
    ],
    seoTitle: "Yacht Charter Athens to Mykonos 2026 | Honest Logistics",
    seoDescription: "Athens-base yacht charter heading to Mykonos. Delivery fee math, embarkation options, 7-day Cyclades itinerary. Direct broker conversation.",
  },

  {
    slug: "yacht-charter-greece-corporate-groups",
    urlPath: "/yacht-charter-greece-corporate-groups",
    eyebrow: "Corporate · Groups",
    h1: "Greek Yacht Charter for Corporate Groups (2026)",
    tagline: "Off-sites, client hosting, milestone events. The discreet, performance-engineered version of corporate hospitality.",
    quickAnswerQ: "What's needed for a corporate yacht charter in Greece?",
    quickAnswerA: "Corporate yacht charters in Greece typically book 40-50m motor yachts (5-6 cabins, 8-10 crew) for 12-guest peak. Common formats: 3-night off-site, 7-night client hosting, 1-week board retreat. Pricing: €220,000-€420,000 per week base for the right yacht. Add 30% APA, Greek VAT at the certified rate, 10-15% gratuity. Full event support (DJ, decor, branded materials) layered through the chef + stewardess team.",
    yachtRecs: [
      { kind: "Motor yacht 40-50m", cabins: "5-6 cabins, 12 guests", crew: "8-10 crew", weekly: "€220,000 - €380,000", fitFor: "Most-balanced corporate spec" },
      { kind: "Superyacht 50-60m", cabins: "6+ cabins", crew: "11-14 crew", weekly: "€380,000 - €650,000", fitFor: "Premium client hosting + helipad" },
    ],
    pricingNote: "Branded materials, DJ, photographer, additional staff onshore typically billed separately (not via APA).",
    itinerary: [
      { day: 1, title: "Embark Athens · Cape Sounion welcome dinner", body: "Board 17:00 Alimos. Welcome cocktail at Cape Sounion sunset. Branded menu cards if requested." },
      { day: 2, title: "Hydra · day at anchor + dinner ashore", body: "Saronic - calm water for board meetings on aft deck. Lunch aboard. Dinner Hydra harbour." },
      { day: 3, title: "Spetses · final morning · disembark", body: "Optional morning meeting onboard. Disembark by 11:00 Spetses port for ferry/helicopter back to Athens." },
    ],
    whyGeorgeYachts: [
      "Discreet sourcing of branded menu cards, photographers, on-deck banners via Athens vendor network - no public association.",
      "Captain matching for corporate calendar: meeting-friendly anchor schedules, not Mykonos-party schedules.",
      "NDAs with crew on request. Standard MYBA confidentiality, optional additional client-specific NDA.",
    ],
    faq: [
      { q: "Can we have a working meeting onboard?", a: "Yes - aft decks at anchor are excellent meeting spaces. Reliable Starlink + 4G/5G across the Greek archipelago. Captain holds calm anchorage on request." },
      { q: "Do corporate charters include event staff?", a: "Standard yacht crew (chef, stewardesses, mate) does service. Additional event staff (DJ, photographer, decorator) added separately by George's vendor network." },
      { q: "Are corporate charters tax-deductible?", a: "Depends on your jurisdiction and use case. Client-hosting on yacht is typically a marketing/business-development expense; team off-sites are typically training/development. Consult your tax advisor; George provides MYBA-standard invoices that satisfy most accounting departments." },
    ],
    seoTitle: "Greek Yacht Charter for Corporate Groups 2026",
    seoDescription: "40-60m yacht charter for corporate off-sites + client hosting. Confidential, branded options. Real Athens-base logistics. George Yachts for boards.",
  },

  {
    slug: "yacht-charter-greece-honeymoon",
    urlPath: "/yacht-charter-greece-honeymoon",
    eyebrow: "Honeymoon",
    h1: "Greek Yacht Charter Honeymoon (2026)",
    tagline: "The yacht, the route, the chef briefs that make a honeymoon week the trip you talk about for forty years.",
    quickAnswerQ: "What's the best yacht charter for a Greek honeymoon?",
    quickAnswerA: "For honeymoons, target a 28-35m motor yacht (2 cabins, 4-5 crew) or 32-40m sailing yacht. Peak July-August base: €85,000-€165,000 per week. Itinerary: 1-2 nights Santorini caldera, 4-5 nights Cyclades (Folegandros, Anafi, Schinoussa), or alternate Saronic + Hydra for shorter charters. Chef pre-brief for surprise menus, champagne service, and proposal-style set-pieces.",
    yachtRecs: [
      { kind: "Motor yacht 28-34m", cabins: "2 cabins (master + VIP)", crew: "4-5 crew", weekly: "€85,000 - €140,000", fitFor: "Intimate, fast, romantic" },
      { kind: "Sailing yacht 32-40m", cabins: "3 cabins (with VIP empty)", crew: "4-5 crew", weekly: "€75,000 - €130,000", fitFor: "Sailing romance + Aegean sunsets" },
      { kind: "Catamaran 50-60ft", cabins: "3-4 cabins", crew: "3-4 crew", weekly: "€55,000 - €95,000", fitFor: "Stability for honeymooners who get queasy" },
    ],
    pricingNote: "Brief George 21+ days before for surprise set-pieces (proposals, anniversaries, milestone toasts). Free service.",
    itinerary: [
      { day: 1, title: "Embark Mykonos · sunset Psarou", body: "Welcome aboard 17:00. Champagne. Sunset dinner at anchor in Psarou or Ornos." },
      { day: 2, title: "Delos · Rineia · private swim", body: "Morning archaeology. Lunch aboard in the channel between Delos and Rineia." },
      { day: 3, title: "Naxos · Mikri Vigla", body: "White-sand beaches. Lunch ashore at Sea Satin." },
      { day: 4, title: "Folegandros · Chora dinner", body: "Cliff-top village - one of Greece's most-romantic evenings." },
      { day: 5, title: "Santorini caldera · Ammoudi sunset", body: "Mooring buoy at Ammoudi. Sunset dinner aboard or ashore at Sunset Ammoudi." },
      { day: 6, title: "Anafi · empty anchorage", body: "The Cyclades' most-isolated inhabited island. Total privacy." },
      { day: 7, title: "Ios · Manganari · return Mykonos", body: "Final beach day. Sea Satin lunch. Disembark Mykonos Day 8." },
    ],
    whyGeorgeYachts: [
      "Honeymoon-tuned chef briefs: specific menus by night, surprise cake setups, champagne pairings, dietary management for both partners.",
      "Proposal logistics: flowers, photographer, custom champagne label, surprise anchor timing. Booked discreetly.",
      "Captain matching: we know which captains run the romantic schedule (sunset anchors, calm-water nights) vs the activity schedule.",
    ],
    faq: [
      { q: "How early should we book a Greek honeymoon?", a: "For peak July-August 2026: by Q1 2026 ideally; mid-May still has mid-tier availability. For 2027 peak: start conversation October 2026." },
      { q: "Can the yacht arrange a proposal?", a: "Yes - flowers, photographer, custom menu, surprise toast at anchor. Brief George 21+ days ahead with specifics. Discretion guaranteed." },
      { q: "Is sailing or motor better for a honeymoon?", a: "Personal preference. Motor yachts: more amenity, faster passages, more private spaces. Sailing yachts: a sailing-into-sunset moment that motor yachts cannot replicate. Most honeymoons we broker choose motor; the sailing crowd knows it specifically." },
    ],
    seoTitle: "Greek Yacht Charter Honeymoon 2026 | Romantic Itineraries",
    seoDescription: "Honeymoon yacht charter Greece. 28-40m yacht, Santorini caldera + Cyclades. Chef briefs, proposal logistics. Romantic specialist George Yachts.",
  },

  {
    slug: "catamaran-charter-greece-family",
    urlPath: "/catamaran-charter-greece-family",
    eyebrow: "Catamaran · Family",
    h1: "Catamaran Charter Greece for Families (2026)",
    tagline: "Catamarans are the family workhorse of Greek chartering. Here's why - and which sizes work for which family shapes.",
    quickAnswerQ: "Why are catamarans the best family yacht in Greece?",
    quickAnswerA: "Catamarans solve three family problems: zero roll at anchor (kids sleep through anchor moves), shallow draft (1.2-1.5m means access to calm-water beaches monohulls cannot enter), and 50% more deck space at the same length (room for kids' activities and parents' chill zone simultaneously). Peak July-August: €35,000-€140,000 per week for 4-6 cabins.",
    yachtRecs: [
      { kind: "Sailing catamaran 50-55ft", cabins: "4 cabins", crew: "3 crew", weekly: "€35,000 - €60,000", fitFor: "Family of 4-6, lower budget" },
      { kind: "Power catamaran 60-80ft", cabins: "4-5 cabins", crew: "3-4 crew", weekly: "€55,000 - €130,000", fitFor: "Larger families, more amenity" },
      { kind: "Luxury catamaran 80-100ft (Sunreef class)", cabins: "5-6 cabins", crew: "5-6 crew", weekly: "€100,000 - €240,000", fitFor: "UHNW families, premium specs" },
    ],
    pricingNote: "Add water-toy kit appropriate to ages (paddleboards 5+, inflatable trampoline kids-friendly, e-foils 12+).",
    itinerary: [
      { day: 1, title: "Embark Corfu · family welcome", body: "Board 17:00 Kassiopi. Family-friendly first dinner aboard." },
      { day: 2, title: "Paxos · Lakka · family bay", body: "Sheltered swim, easy beach access via tender." },
      { day: 3, title: "Antipaxos · Voutoumi", body: "Best children's swimming water in Greece. Crystal-clear." },
      { day: 4, title: "Lefkada · Porto Katsiki", body: "Iconic Ionian beach. Long swim afternoon." },
      { day: 5, title: "Meganisi · Spilia + Ambelaki", body: "Family-friendly small island. Tavernas, easy access." },
      { day: 6, title: "Kefalonia · Foki + Antisamos", body: "Mamma Mia coast. Family-friendly bay structure." },
      { day: 7, title: "Return Corfu · Agni dining", body: "Final lunch at Agni's family-friendly tavernas. Disembark." },
    ],
    whyGeorgeYachts: [
      "Family-tested catamaran inventory - we know which yachts have kid-friendly cabin layouts (no shared baths, parent-master separation).",
      "Children's-programme stewardess matching when families request dedicated kids' staff.",
      "Ionian routing default for families with kids under 10 (no Meltemi, calmer passages).",
    ],
    faq: [
      { q: "Sailing vs power catamaran for family?", a: "Sailing catamarans: lower cost, slower (good for relaxed pace), sailing experience itself. Power catamarans: faster passages, quieter at anchor (no rigging noise), more cabin amenity. Most family bookings choose power for the practical reasons." },
      { q: "Are catamarans safer for children?", a: "More stable. Zero roll at anchor and significantly less roll underway. Less likely to trigger motion sickness. Safety equipment is identical to monohulls under MYBA standards." },
      { q: "Catamaran cabin sizes for family of 4?", a: "Most family-charter catamarans have 4 large cabins, each with private bath. Master cabin typically gets the largest. Kids' cabins are roomy enough for two singles or one double. Total space per family member is dramatically more than equivalent-length monohull." },
    ],
    seoTitle: "Catamaran Charter Greece for Families 2026 | Why Cats Win",
    seoDescription: "Catamaran charter Greece for families with kids: zero roll, shallow draft, 50% more deck space. Sailing vs power. Real pricing. From George Yachts.",
  },

  {
    slug: "superyacht-charter-greece-august",
    urlPath: "/superyacht-charter-greece-august",
    eyebrow: "Superyacht · August",
    h1: "Superyacht Charter Greece in August (2026)",
    tagline: "August in the Aegean on a 50m+ yacht is the most-requested charter on earth. Here is the reality of fleet, pricing, and availability.",
    quickAnswerQ: "Can I charter a superyacht in Greece in August 2026?",
    quickAnswerA: "Yes, but with constraints. As of mid-May 2026, 50m+ Greek superyacht availability for August is effectively closed (94% committed). 70m+ megayacht availability requires repositioning from Monaco/Antibes (delivery surcharge). 40-50m availability remains for the right yacht. Peak August base rates: €380,000-€780,000 per week for 50-70m; €780,000-€1,800,000 for 70m+.",
    yachtRecs: [
      { kind: "Superyacht 50-60m", cabins: "6+ cabins", crew: "11-14 crew", weekly: "€380,000 - €650,000", fitFor: "Standard premium August charter" },
      { kind: "Megayacht 60-80m", cabins: "7+ cabins", crew: "15-22 crew", weekly: "€650,000 - €1,300,000", fitFor: "Upper-tier with helipad, beach club" },
      { kind: "Gigayacht 80-100m+", cabins: "8-12 cabins", crew: "20-30+ crew", weekly: "€1,300,000 - €2,500,000+", fitFor: "Top 30 yachts globally" },
    ],
    pricingNote: "August Greek peak is the Mediterranean's most-expensive moment. APA scales to 30% on €500k+ rates means €150k+ in working float.",
    itinerary: [
      { day: 1, title: "Embark Mykonos · party island arrival", body: "Board 17:00. Welcome aboard. Possible helipad arrival." },
      { day: 2, title: "Mykonos · Nammos + Delos", body: "Beach club + archaeology day. Sunset back at Ornos." },
      { day: 3, title: "Naxos · Folegandros", body: "Cross south. Dramatic Cycladic scenery." },
      { day: 4, title: "Santorini caldera · sunset moment", body: "Mooring buoy at Ammoudi. Sunset dinner aboard or at Sunset Ammoudi." },
      { day: 5, title: "Anafi · empty anchorage privacy", body: "Off-grid morning. The Cyclades' most-isolated inhabited island." },
      { day: 6, title: "Ios · Manganari · Mykonos final dinner", body: "Final Mykonos evening. JackieO if relevant social calendar fits." },
      { day: 7, title: "Return Mykonos · disembark", body: "Final morning. Helicopter or ferry transfer to Athens." },
    ],
    whyGeorgeYachts: [
      "Greek-flagged superyacht specialist. We know which 50m+ yachts have August availability before they appear in any public broker channel.",
      "Direct relationships with megayacht management firms (Camper & Nicholsons, Burgess, Fraser, Edmiston) for 70m+ tier.",
      "Greek-port priority bookings: Mykonos Marina, Santorini caldera moorings, Hydra harbour - all relationship-managed.",
    ],
    faq: [
      { q: "Is August 2026 really sold out?", a: "Mid-tier 30-40m: ~22% available as of mid-May. 50m+ superyachts: ~6% available. 70m+ megayachts: effectively closed for Greek embark. For 2027 peak, contact George by October 2026." },
      { q: "Should I wait until 2027 vs forcing 2026?", a: "If yacht spec is non-negotiable (specific yacht or specific size), 2027 is the cleaner path. If flexible on yacht spec or willing to consider shoulder season alternatives, 2026 is still bookable in mid-tier." },
      { q: "What about September instead?", a: "Late September Cyclades and October Saronic still have ~25% top-tier availability. Same warm water, no Meltemi, 18-32% lower rates than August peak. Excellent alternative." },
    ],
    seoTitle: "Superyacht Charter Greece August 2026 | Pricing",
    seoDescription: "50m+ superyacht charter Greece August 2026. Honest availability (96% committed), real pricing €380k-1.8M+. Alternatives if August is closed.",
  },

  {
    slug: "yacht-charter-greece-with-stabilizers",
    urlPath: "/yacht-charter-greece-with-stabilizers",
    eyebrow: "Stabilisers · Comfort",
    h1: "Greek Yacht Charter with Stabilisers (2026)",
    tagline: "Stabilisers are the single largest comfort variable on any yacht. Here is what they do, which yachts have modern ones, and why it matters in Greece.",
    quickAnswerQ: "Are stabilisers necessary on a Greek yacht charter?",
    quickAnswerA: "Yes if motion sickness is a real risk in your party. Modern zero-speed gyroscopic stabilisers (Seakeeper) reduce roll from 5-8 degrees to under 1 degree at anchor. Critical for Meltemi-affected Cyclades summer chartering. Most Greek motor yachts built 2018+ have stabilisers; older yachts vary. Charter rate impact: minimal (+5% premium typical).",
    yachtRecs: [
      { kind: "Motor yacht 28-35m with Seakeeper", cabins: "3-4 cabins", crew: "5-6 crew", weekly: "€110,000 - €180,000", fitFor: "Modern build + premium stabilisation" },
      { kind: "Motor yacht 35-50m with twin gyros", cabins: "4-5 cabins", crew: "7-10 crew", weekly: "€180,000 - €420,000", fitFor: "Maximum-comfort stabilised" },
    ],
    pricingNote: "Always ask: 'Is it zero-speed capable?' Not all stabilisers work at anchor.",
    itinerary: [
      { day: 1, title: "Embark Mykonos · stabiliser-tested first dinner", body: "Anchor Ornos. Stabilisers engaged. Test dinner aboard - plates stay where placed." },
      { day: 2, title: "Tinos · meltemi day · stabilised lunch", body: "Light Meltemi day. Lunch on aft deck without bracing." },
      { day: 3, title: "Naxos · open Cyclades passage", body: "Cross-Cyclades passage. Stabilised even at 12 knots." },
      { day: 4, title: "Folegandros · sunset at Chora", body: "Anchor Karavostasis. Zero roll. Sunset cocktails outdoor." },
      { day: 5, title: "Santorini caldera · mooring", body: "Caldera evening. Zero roll dinner at anchor with sunset view." },
      { day: 6, title: "Ios · Manganari", body: "Family swim day. Stabilisers irrelevant - calm bay. Toys time." },
      { day: 7, title: "Return Mykonos via Paros", body: "Final passage. Stabilisers prove value on the long return run." },
    ],
    whyGeorgeYachts: [
      "Stabiliser-vetted inventory: every yacht in our private fleet has confirmed zero-speed stabiliser specifications.",
      "Generation-aware: we flag the 1-2 yachts in inventory with older fin-only systems so motion-sensitive guests choose appropriately.",
      "Meltemi-routing captains who use stabilisers strategically (engaged on Meltemi days, off in calm bays to save fuel).",
    ],
    faq: [
      { q: "Do stabilisers consume fuel?", a: "Gyroscopic systems consume electricity (3-10kW) which means the generator runs slightly more. Fuel cost over a full charter: ~€200-€500 incremental. Negligible vs the comfort gain." },
      { q: "Does the captain decide when to engage stabilisers?", a: "Usually engaged whenever guests are aboard at anchor or in any swell. Captain may disengage in flat-calm conditions to save fuel - the guest can always ask for them on." },
      { q: "Are stabilisers retrofitted on older yachts?", a: "Some - Seakeeper retrofits became common 2018+. Pre-2015 yachts often still have fin-only systems (effective underway, less effective at anchor). Always ask specifically." },
      // 2026-06-10 GSC-driven: real query "what are stabilizing fins
      // for yachts and motorboats?" + the page previously used only
      // the British spelling; this answer adds the American forms
      // (stabilizers / stabilizing) for the US-spelling query set.
      { q: "What are stabilizing fins for yachts and motor boats?", a: "Stabilizing fins are underwater appendages, active or passive, that counteract roll while the yacht is underway. Modern Greek charter yachts increasingly pair fins with zero-speed gyroscopic stabilizers (Seakeeper), which work at anchor where fins cannot. If your party is motion-sensitive, ask for both systems: fins for the passages, gyros for the anchorages." },
    ],
    seoTitle: "Greek Yacht Charter with Stabilisers 2026 | Why They Matter",
    seoDescription: "Yachts with modern Seakeeper / zero-speed stabilisers for Greek chartering. Critical for Meltemi-aware comfort. Pricing impact, retrofitted yachts.",
  },

  {
    slug: "last-minute-yacht-charter-greece-2026",
    urlPath: "/last-minute-yacht-charter-greece-2026",
    eyebrow: "Last minute · 2026",
    h1: "Last-Minute Yacht Charter Greece (2026)",
    tagline: "Last-minute Greek charter is possible but constrained. The honest playbook for booking within 4 weeks of departure.",
    quickAnswerQ: "Can I still book a Greek yacht charter at the last minute in 2026?",
    quickAnswerA: "Yes, with constraints. Peak July-August 2026 is 91% committed as of mid-May - last-minute (under 4 weeks) options are 24-35m motor yachts or catamarans, rarely 40m+. Shoulder season (June, September) has stronger last-minute availability across all tiers. Late September and October Saronic are the genuine last-minute value windows.",
    yachtRecs: [
      { kind: "Motor yacht 24-30m last-minute", cabins: "3-4 cabins", crew: "4-5 crew", weekly: "€65,000 - €110,000 (often with 5-15% premium)", fitFor: "Peak season last-minute" },
      { kind: "Catamaran 50-60ft last-minute", cabins: "4 cabins", crew: "3 crew", weekly: "€35,000 - €70,000", fitFor: "Best peak last-minute value" },
      { kind: "Any 30-40m yacht for shoulder September/October", cabins: "4-5 cabins", crew: "5-8 crew", weekly: "Standard rates, no premium", fitFor: "If your dates are flexible" },
    ],
    pricingNote: "Last-minute peak: 5-15% premium typical. Shoulder: standard pricing or occasional 5-10% concession.",
    itinerary: [
      { day: 1, title: "Same-week embark · Athens flexible", body: "Athens-base yachts can confirm same-week embark within 48-72 hours." },
      { day: 2, title: "Cycladic skip - what's reachable last-minute", body: "Saronic + Cyclades reachable on standard 7-night last-minute charter from Athens base." },
      { day: 3, title: "Adjust to available anchorages", body: "Some marinas in peak August are fully booked - anchor instead of marina." },
    ],
    whyGeorgeYachts: [
      "Last-minute availability tracker updated daily across our fleet. Real availability, not stale.",
      "Athens-base relationship means we can confirm embark within 48 hours on most mid-tier yachts.",
      "Honest about what's NOT available - we don't show you yachts we can't deliver in your timeframe.",
    ],
    faq: [
      { q: "How fast can a charter be confirmed?", a: "Standard last-minute path: inquiry → yacht options within 24 hours → contract within 72 hours → deposit + APA wire within 7 days → embark 14+ days out. Compressed timeline: contract + deposit same week, embark same week if the yacht has availability and the operator accepts compressed terms." },
      { q: "Is last-minute always more expensive?", a: "Peak season last-minute: typically 5-15% above original quoted rates (scarcity premium). Shoulder season last-minute: standard rates or occasional concession." },
      { q: "What documents do I need to charter at the last minute?", a: "Passport scans for every guest, completed preference sheet, signed MYBA contract, wire confirmation for deposit + APA. Total ~3-5 documents. George guides you through all of them within 48 hours of inquiry." },
    ],
    seoTitle: "Last-Minute Yacht Charter Greece: What Is Genuinely Still Bookable (2026)",
    seoDescription: "Last-minute Greek yacht charter 2026: honest availability per yacht tier, real timelines, what to expect on pricing. From George Yachts.",
  },

  {
    slug: "yacht-charter-greece-american-clients",
    urlPath: "/yacht-charter-greece-american-clients",
    eyebrow: "American clients",
    h1: "Greek Yacht Charter for American Clients (2026)",
    tagline: "Greek-charter expectations for American UHNW: VAT vs sales-tax framing, MYBA vs US legal, EU regulatory comfort, return-flight logistics.",
    quickAnswerQ: "How does Greek yacht charter work for American clients?",
    quickAnswerA: "Greek charter for US clients runs under MYBA-standard contracts (English law, London arbitration) and Greek VAT at the yacht's certified rate. Most US clients fly Athens via direct from JFK/EWR or via Frankfurt/Heathrow. Athens-base embarkation saves the Mykonos delivery surcharge that US travel agents often miss. George Yachts operates from a Wyoming LLC, simplifying contracting for US clients.",
    yachtRecs: [
      { kind: "Motor yacht 35-50m", cabins: "5 cabins, family of 8-10", crew: "8-10 crew", weekly: "€220,000 - €380,000", fitFor: "Standard US family spec" },
      { kind: "Superyacht 50-70m", cabins: "6+ cabins", crew: "11-14 crew", weekly: "€380,000 - €1,200,000", fitFor: "Multi-generational family or UHNW client hosting" },
    ],
    pricingNote: "USD-EUR exchange volatility: lock the deposit early in the year for budgetary certainty.",
    itinerary: [
      { day: 1, title: "Athens arrival · embark same-day", body: "JFK direct flights land Athens 08:30. Hotel for shower + change. Board 17:00 Alimos." },
      { day: 2, title: "Cape Sounion + Kea", body: "First-night Sounion sunset. Day-2 to Kea for swimming start." },
      { day: 3, title: "Mykonos arrival · Psarou day", body: "Cross to Mykonos. Beach club lunch at Nammos. Sunset Ornos." },
      { day: 4, title: "Delos + Tinos", body: "Morning archaeology. Tinos food evening." },
      { day: 5, title: "Naxos + Paros · Cyclades core", body: "South Naxos beach day. Paros village evening." },
      { day: 6, title: "Antiparos channel + Folegandros", body: "Final Cyclades highlight." },
      { day: 7, title: "Santorini caldera or return Athens", body: "Optional Santorini final dinner. Or direct return Athens for Day-8 disembark + flight home." },
    ],
    whyGeorgeYachts: [
      "Wyoming-LLC contracting simplifies US client paperwork and tax treatment.",
      "US-Greek time-zone-aware response (Athens 9am = NYC 2am, but we cover both windows).",
      "Direct AmEx Centurion + JPMorgan Reserve preferred-vendor relationships (no special card-acceptance fees).",
    ],
    faq: [
      { q: "Can I pay in USD or only EUR?", a: "Yacht charter contracts are in EUR (Greek VAT) but US clients can wire USD with auto-conversion. AmEx Centurion / Chase Reserve cards waive FX fees on payments." },
      { q: "Do I need EU travel documents?", a: "US passports allow 90-day visa-free Schengen entry. No advance visa needed for Greek charter." },
      { q: "What about flight logistics?", a: "Direct JFK-Athens flights (Delta, United, American) take 9-10 hours. EWR-Athens routes via Frankfurt/Heathrow common. We can coordinate same-day yacht boarding for arrivals before 14:00." },
    ],
    seoTitle: "Greek Yacht Charter for American Clients 2026 | US-Friendly",
    seoDescription: "Greek yacht charter logistics for American UHNW: MYBA contracts, Wyoming LLC, USD payment, JFK direct flights. From George Yachts US partner.",
  },

  {
    slug: "yacht-charter-greece-uk-clients",
    urlPath: "/yacht-charter-greece-uk-clients",
    eyebrow: "UK clients",
    h1: "Greek Yacht Charter for UK Clients (2026)",
    tagline: "Greek-charter logistics for UK UHNW: post-Brexit travel, GBP-EUR pricing, MYBA familiarity, London-Athens timing.",
    quickAnswerQ: "How does Greek yacht charter work for UK clients post-Brexit?",
    quickAnswerA: "Greek charter for UK clients runs as before: MYBA-standard contracts (English law, London arbitration), Greek VAT at the yacht's certified rate. Post-Brexit, UK passports get 90-day Schengen entry without visa. London-Athens direct flights 3.5 hours. UK clients are familiar with MYBA - same contract framework as French Riviera and Italian charters they may have done.",
    yachtRecs: [
      { kind: "Motor yacht 35-45m", cabins: "5 cabins", crew: "8-10 crew", weekly: "€220,000 - €330,000", fitFor: "Standard UK family / friends group" },
      { kind: "Sailing yacht 40-50m", cabins: "4-5 cabins", crew: "5-7 crew", weekly: "€150,000 - €280,000", fitFor: "UK sailing community spec" },
    ],
    pricingNote: "GBP-EUR rate impact: ~5-8% difference vs 12 months ago. Lock the deposit early for certainty.",
    itinerary: [
      { day: 1, title: "London arrival Athens · embark same day", body: "BA / easyJet direct flights land Athens 13:30. Board 17:00 Alimos." },
      { day: 2, title: "Saronic islands · short charter format", body: "Athens Riviera to Hydra. Short Saronic format works for 4-night UK weekend." },
      { day: 3, title: "Hydra · car-free village", body: "Famous Hydra moored evening. Restaurants ashore." },
      { day: 4, title: "Spetses · seaside village", body: "Bouboulina house, restaurants, walking trails." },
      { day: 5, title: "Poros · Vouliagmeni return", body: "Final island day. Return Athens for disembark + evening flight home." },
    ],
    whyGeorgeYachts: [
      "London office (+44 203 769 2707) covers same-day inquiries from UK timezone.",
      "MYBA-standard contracts familiar to UK family-office and private-banking workflows.",
      "Post-Brexit travel guidance: passport, visa, payment-card considerations covered upfront.",
    ],
    faq: [
      { q: "Are UK card payments accepted by Greek operators?", a: "Yes - Greek charter operators accept all major UK cards (AmEx, Visa, Mastercard) at same fees as before Brexit. Some prefer wire transfer for amounts over €50k." },
      { q: "Has Brexit changed yacht-charter VAT for UK clients?", a: "No - Greek charter VAT applies at the yacht's certified rate regardless of guest nationality. Pre-Brexit and post-Brexit treatment identical for charterers." },
      { q: "Short-charter formats from London?", a: "Yes - the Saronic Gulf 4-night format (Athens Friday, Hydra Saturday, Spetses Sunday, return Athens Tuesday) is the standard London short-trip Greek charter. 30m motor yachts available at €40-60k base for short charters." },
    ],
    seoTitle: "Greek Yacht Charter for UK Clients 2026 | Post-Brexit Guide",
    seoDescription: "Greek yacht charter logistics for UK clients: MYBA contracts, GBP-EUR pricing, London-Athens flights, Saronic short formats. George Yachts London desk.",
  },

  {
    slug: "yacht-charter-dodecanese-rhodes",
    urlPath: "/yacht-charter-dodecanese-rhodes",
    eyebrow: "Dodecanese · Rhodes",
    h1: "Yacht Charter Dodecanese from Rhodes (2026)",
    tagline: "The Dodecanese yacht charter is the under-marketed Greek alternative. Rhodes-based, less-trafficked, culturally distinct.",
    quickAnswerQ: "What's a Dodecanese yacht charter from Rhodes like?",
    quickAnswerA: "Dodecanese charters from Rhodes cover Symi, Halki, Tilos, Nisyros, Kos, Patmos - 12 inhabited islands across a 200nm corridor. Less yacht traffic than Cyclades, deeper cultural layering (Crusader castles, Italian-era architecture, Ottoman influence). Rhodes-base 30-40m yachts: €110,000-€240,000 per week peak. Or 40-50m for upper-tier: €220,000-€380,000.",
    yachtRecs: [
      { kind: "Motor yacht 30-40m (Rhodes base)", cabins: "4-5 cabins", crew: "6-8 crew", weekly: "€110,000 - €240,000", fitFor: "Standard Dodecanese spec" },
      { kind: "Sailing yacht 35-45m", cabins: "4-5 cabins", crew: "5-6 crew", weekly: "€95,000 - €180,000", fitFor: "Quieter Dodecanese pace, lower cost" },
    ],
    pricingNote: "Rhodes-base means no delivery from Athens needed. Saves €5-10k vs Athens-base + Dodecanese itinerary.",
    itinerary: [
      { day: 1, title: "Embark Rhodes · Old Town evening", body: "Rhodes Mandraki harbour. Medieval Old Town dinner ashore." },
      { day: 2, title: "Symi · harbour town", body: "Greece's prettiest harbour. Italian-era architecture. Restaurants on the waterfront." },
      { day: 3, title: "Halki + Tilos · empty islands", body: "Less-trafficked Dodecanese. Empty anchorages. Pure swimming." },
      { day: 4, title: "Nisyros · volcanic crater", body: "Active volcano island. Crater walk. Mandraki village." },
      { day: 5, title: "Kos · Hippocrates connection", body: "Cosmopolitan island. Asklepion archaeological site. Marina-based dinner." },
      { day: 6, title: "Patmos · monastery + Apocalypse cave", body: "UNESCO. The most-significant Christian site outside Israel. Quiet anchorage." },
      { day: 7, title: "Return Rhodes · final evening", body: "Long return passage. Final Old Town dinner before disembark." },
    ],
    whyGeorgeYachts: [
      "Dodecanese specialist routes - we have direct relationships with Rhodes harbour authority and the Symi taverna network.",
      "Less-trafficked alternative when peak Cyclades feels overwhelming.",
      "Italian + Ottoman cultural depth - we brief clients on which sites are worth which excursion type.",
    ],
    faq: [
      { q: "Is the Dodecanese cheaper than the Cyclades?", a: "Slightly. Rhodes-base yachts run 10-15% below equivalent Cyclades-base yachts due to less peak demand. Lower marina fees in Dodecanese ports also help APA." },
      { q: "Can I combine Dodecanese + Cyclades?", a: "Operationally possible but consumes 2 days passage time each way. Better as separate charters in different years." },
      { q: "What about Turkish coast from Rhodes?", a: "Symi is 20nm from Datça (Turkey). Cross-border charters technically possible but Turkish-flag rules + customs add complexity. Most Dodecanese clients stay all-Greek." },
      // 2026-06-10 GSC-driven: "motor yacht dodecanese" at pos 13.2
      // had no exact-match answer on the page.
      { q: "Which motor yachts work best for the Dodecanese?", a: "Rhodes-based motor yachts in the 30-40m range are the standard Dodecanese platform: the 200nm island corridor rewards 20-knot passage speed, and a Rhodes base means no Athens delivery fee. Peak-week pricing runs €110,000-€240,000. For the tighter harbours of Symi, Halki and Tilos, shallower-draft motor yachts under 35m open more mooring options." },
    ],
    seoTitle: "Yacht Charter Rhodes & Dodecanese 2026 | Symi, Kos, Patmos",
    seoDescription: "Dodecanese yacht charter from Rhodes: Symi, Patmos, Kos, Nisyros, Tilos. The quieter Greek alternative, with real 2026 pricing and a full week itinerary.",
  },

  {
    slug: "yacht-charter-sporades-skiathos",
    urlPath: "/yacht-charter-sporades-skiathos",
    eyebrow: "Sporades · Skiathos",
    h1: "Yacht Charter Sporades from Skiathos (2026)",
    tagline: "The Sporades is the Mamma Mia Greek charter. Pine-covered, family-friendly, less-trafficked than the Cyclades.",
    quickAnswerQ: "Why charter a yacht in the Sporades vs the Cyclades?",
    quickAnswerA: "Sporades (Skiathos, Skopelos, Alonnisos) offers Mamma Mia scenery, pine forests, family-friendly calm-water beaches, and 30% fewer yachts than the Cyclades. Less wind than the Aegean. Pricing 15-20% below Cyclades equivalent. Charter base: Skiathos or Volos. 30-40m motor yachts: €85,000-€180,000 peak weekly.",
    yachtRecs: [
      { kind: "Motor yacht 30-40m (Skiathos base)", cabins: "4-5 cabins", crew: "6-8 crew", weekly: "€85,000 - €180,000", fitFor: "Standard Sporades spec" },
      { kind: "Sailing yacht 35-45m", cabins: "4-5 cabins", crew: "5-6 crew", weekly: "€75,000 - €150,000", fitFor: "Sailing pace, lower budget" },
      { kind: "Catamaran 50-60ft", cabins: "4 cabins", crew: "3-4 crew", weekly: "€35,000 - €70,000", fitFor: "Family-friendly Sporades" },
    ],
    pricingNote: "Skiathos-base yachts are limited - confirm availability before set dates.",
    itinerary: [
      { day: 1, title: "Embark Skiathos · Koukounaries beach", body: "Most-photographed Greek beach. Pine-fringed crescent. First swim." },
      { day: 2, title: "Skopelos · Mamma Mia coast", body: "Agnontas village, Glysteri bay, Mamma Mia church (Agios Ioannis)." },
      { day: 3, title: "Alonnisos · marine park", body: "Alonnisos Marine Park - dolphin sightings. Patitiri village evening." },
      { day: 4, title: "Skantzoura + Peristera · uninhabited islands", body: "Day swim at uninhabited Sporades islands. Pure isolation." },
      { day: 5, title: "Skopelos · Klima village", body: "Cliff-village evening. Restaurants ashore." },
      { day: 6, title: "Skiathos · Lalaria beach", body: "White-pebble dramatic beach, tender-access only." },
      { day: 7, title: "Return Skiathos · final dinner", body: "Skiathos town dinner. Disembark Day 8." },
    ],
    whyGeorgeYachts: [
      "Skiathos-base partnership - we handle direct contracting with local operators for Sporades-only itineraries.",
      "Mamma Mia tour design - if requested, we route through the specific film locations.",
      "Calm-water family expertise - the Sporades is the Greek answer for families nervous about Cyclades wind.",
    ],
    faq: [
      { q: "Is the Sporades better than the Cyclades for families?", a: "If your priority is calm water + family swimming, yes. The Sporades is wind-protected, the bays are sheltered, and the islands are closer together. The Cyclades has more cultural depth and dramatic landscapes but more wind." },
      { q: "Can we sail to the Cyclades from the Sporades?", a: "Possible but expensive - ~150nm and 1-2 days passage each way. Better to keep the charter within the Sporades or do two separate charters." },
      { q: "When's the best time for the Sporades?", a: "June-September. Calm summers throughout. Late September is the quietest sweet spot - pine air, warm water, few yachts." },
    ],
    seoTitle: "Yacht Charter Sporades from Skiathos 2026 | Mamma Mia Coast",
    seoDescription: "Sporades yacht charter: Skiathos, Skopelos, Alonnisos. Mamma Mia coast, family-friendly bays, 15-20% below Cyclades pricing. Skiathos-base specialist.",
  },

  {
    slug: "crewed-catamaran-charter-cyclades",
    urlPath: "/crewed-catamaran-charter-cyclades",
    eyebrow: "Crewed catamaran · Cyclades",
    h1: "Crewed Catamaran Charter in the Cyclades (2026)",
    tagline: "Catamarans access Cyclades anchorages monohulls cannot - shallow-draft white-sand crescents the rest of the fleet misses.",
    quickAnswerQ: "Why charter a crewed catamaran in the Cyclades specifically?",
    quickAnswerA: "Catamarans have 1.2-1.5m draft vs 2.4-3m on monohulls. In the Cyclades that means access to Donousa, Iraklia shallows, Despotiko channel, Soros (Antiparos), Mikri Vigla (Naxos) - the iconic shallow-water anchorages. Plus zero roll on Meltemi days at south-coast anchorages. Crewed catamaran 50-65ft: €55,000-€130,000 per week peak.",
    yachtRecs: [
      { kind: "Sailing catamaran 50-55ft (crewed)", cabins: "4 cabins", crew: "3 crew", weekly: "€55,000 - €85,000", fitFor: "Standard Cyclades catamaran" },
      { kind: "Power catamaran 60-80ft", cabins: "4-5 cabins", crew: "4-5 crew", weekly: "€85,000 - €180,000", fitFor: "Premium amenity, fastest" },
      { kind: "Luxury catamaran 80-100ft", cabins: "5-6 cabins", crew: "5-6 crew", weekly: "€140,000 - €240,000", fitFor: "Sunreef class, UHNW spec" },
    ],
    pricingNote: "Catamarans have wider beam - some Cyclades marinas charge 1.5x monohull rates. Anchoring is preferred anyway.",
    itinerary: [
      { day: 1, title: "Embark Mykonos · Ornos sunset", body: "Welcome aboard 17:00. Anchor Ornos. Catamaran stability immediately evident." },
      { day: 2, title: "Delos + Rineia · shallow swimming", body: "Anchor in the channel between Delos and Rineia. Crystal-clear shallow water." },
      { day: 3, title: "Naxos · Mikri Vigla", body: "Shallow-draft access to white-sand crescent. Monohulls anchor far offshore here." },
      { day: 4, title: "Schinoussa · empty anchorage", body: "Total privacy. Catamaran shallow-draft = closer-to-beach anchoring." },
      { day: 5, title: "Donousa + Iraklia · shallows", body: "Donousa main anchorage 1.8m depth - perfect for catamaran. Monohulls cannot enter." },
      { day: 6, title: "Antiparos channel · Soros", body: "The Cyclades' most-beautiful turquoise. Catamaran day at Soros." },
      { day: 7, title: "Paros + return Mykonos", body: "Naoussa evening. Final return passage." },
    ],
    whyGeorgeYachts: [
      "Cyclades-cat specialist - we know which catamarans handle the long Cyclades passages best in Meltemi.",
      "Shallow-anchorage routing: our captains know Donousa shoals, Despotiko underwater obstacles, Mikri Vigla depth contours.",
      "Family + corporate matching: catamarans serve both well; we tune captain + crew to the audience.",
    ],
    faq: [
      { q: "Is a catamaran slower than a monohull motor yacht?", a: "Sailing catamarans: yes - 8-10 knots cruise. Power catamarans: comparable at 14-18 knots. For passage-heavy itineraries (Cyclades cross-archipelago), power catamarans match monohulls." },
      { q: "Can catamarans handle Meltemi?", a: "Yes. Stability under wind is excellent. Routing onto southern anchorages on Meltemi days remains the strategy - same as for monohulls." },
      { q: "Marina fees on Cyclades catamarans?", a: "Some marinas charge 1.3-1.5x monohull rate. Most Cyclades anchorages are anchorage-only anyway, so this is rarely a real cost driver." },
    ],
    seoTitle: "Crewed Catamaran Charter Cyclades 2026 | Shallow Draft",
    seoDescription: "Crewed catamaran Cyclades: Donousa, Despotiko, Mikri Vigla, Soros. Shallow-draft access monohulls miss. Real pricing, captain routing.",
  },

  {
    slug: "motor-yacht-charter-saronic-gulf",
    urlPath: "/motor-yacht-charter-saronic-gulf",
    eyebrow: "Motor yacht · Saronic",
    h1: "Motor Yacht Charter in the Saronic Gulf (2026)",
    tagline: "The Saronic Gulf is Athens's home waters. Short formats, wind-stable, Hydra and Spetses in 4 nights.",
    quickAnswerQ: "Is the Saronic Gulf a real Greek yacht charter destination?",
    quickAnswerA: "Yes - and underrated. The Saronic (Hydra, Spetses, Poros, Aegina) is wind-protected (no Meltemi), Athens-reachable (no flight transfer needed), and supports short 4-night formats UHNW clients use for weekend escapes. Motor yacht 30-40m: €110,000-€220,000 per week base. 4-night charters run ~60-70% of weekly rate. Iconic stop: Hydra harbour mooring.",
    yachtRecs: [
      { kind: "Motor yacht 30-40m", cabins: "4-5 cabins", crew: "6-8 crew", weekly: "€110,000 - €220,000", fitFor: "Standard Saronic spec" },
      { kind: "Performance motor yacht 24-30m", cabins: "3 cabins", crew: "4-5 crew", weekly: "€55,000 - €110,000", fitFor: "Short format, fast" },
    ],
    pricingNote: "4-night Saronic short-format = ~65% of weekly rate. Adds value for Athens-base UHNW.",
    itinerary: [
      { day: 1, title: "Embark Athens Alimos · Aegina overnight", body: "Board 17:00. Aegina (1hr) for first evening. Pistachio capital of Greece." },
      { day: 2, title: "Poros · island village + Russian Cape", body: "Poros town, walk to Russian Cape lighthouse for sunset." },
      { day: 3, title: "Hydra · harbour mooring", body: "Hydra arrival. Stern-to mooring in the famous harbour. Dinner ashore at Sunset or Omilos." },
      { day: 4, title: "Hydra · Vlychos beach + walking trails", body: "Donkey-only island - walk to Vlychos for lunch. Famous taverna ashore." },
      { day: 5, title: "Spetses · island village", body: "Spetses town, Bouboulina house, beach taverna lunch." },
      { day: 6, title: "Spetses · final evening", body: "Final Saronic evening. Restaurant ashore at the harbour." },
      { day: 7, title: "Return Athens · disembark", body: "Final morning at Spetses or Poros. Return Alimos for disembark Day 8." },
    ],
    whyGeorgeYachts: [
      "Saronic specialist - we know which yachts handle the short 4-night format and which need full 7-night minimum.",
      "Hydra harbour mooring relationships - direct port authority contact for mooring assignment.",
      "Athens-base means no delivery surcharge - the cleanest economic Greek charter from Athens.",
    ],
    faq: [
      { q: "Can I do a 3-night Saronic charter?", a: "Some operators yes (~50% of weekly rate). Most prefer 4-night minimum. Very short formats work for Athens-based event hosting (Friday night, Saturday day, Sunday brunch, Monday disembark)." },
      { q: "Saronic vs Cyclades for first-time Greek charter?", a: "Saronic for first-time + short charter + Athens-base + wind-averse. Cyclades for iconic landscapes + longer charters + photographic destinations." },
      { q: "Is October still good for the Saronic?", a: "Excellent. Water 22°C through mid-October. Restaurants still open. Few yachts. October Saronic pricing 30-40% below July peak. Hidden value." },
    ],
    seoTitle: "Motor Yacht Charter Saronic Gulf 2026 | Hydra + Spetses",
    seoDescription: "Saronic Gulf motor yacht charter: Hydra harbour mooring, Spetses, Poros, Aegina. 4-night short formats. Athens-base, no Meltemi. Real pricing.",
  },
  // ─── 2027 season-net pages (2026-07-21) ─────────────────────────────────
  // Early-Bird 2027 wave: catch the 6-12-months-out planner searching a
  // specific 2027 month. Pricing bands = the 2026 Charter Index reference,
  // labelled as such (owners publish 2027 cards in autumn 2026 - never
  // invent 2027 numbers). Each page funnels to /yacht-charter-greece-2027
  // and /inquiry. Itinerary stops are real anchorages already used across
  // the site - nothing invented.

  {
    slug: "yacht-charter-greece-june-2027",
    urlPath: "/yacht-charter-greece-june-2027",
    eyebrow: "June 2027 · The Connoisseur's Value",
    h1: "Yacht Charter in Greece, June 2027",
    tagline: "The longest days of the year, warm air, rates a step below peak - and for American families, the smart pre-rush window.",
    quickAnswerQ: "Is June a good month for a Greek yacht charter, and when should I book June 2027?",
    quickAnswerA: "June is the connoisseur's month: the longest daylight of the year, a warming sea, and weekly rates typically a step below the July-August peak. For June 2027, the practical booking window is autumn 2026 through early winter - owners publish 2027 rate cards in autumn, and the best late-June weeks travel with the US school calendar, so they go early. Reference pricing (2026 Index): crewed catamarans roughly EUR 15,000-40,000 per week net; motor yachts 24-34m EUR 30,000-100,000.",
    yachtRecs: [
      { kind: "Crewed sailing catamaran", cabins: "4-5 cabins", crew: "3-6 crew", weekly: "€15,000 - €40,000 (2026 ref.)", fitFor: "Families easing into the season" },
      { kind: "Motor yacht 24-34m", cabins: "4-6 cabins", crew: "5-8 crew", weekly: "€30,000 - €100,000 (2026 ref.)", fitFor: "Covering more islands in the long days" },
      { kind: "Crewed sailing monohull", cabins: "3-4 cabins", crew: "2-4 crew", weekly: "from €11,000 (2026 ref.)", fitFor: "Purists - June winds are kind" },
    ],
    pricingNote: "2026 Charter Index reference bands; owners publish 2027 rate cards in autumn 2026. Add VAT at the yacht's certified rate and APA.",
    itinerary: [
      { day: 1, title: "Athens (Alimos) · Poros", body: "Board late afternoon, short first hop to Poros. Dinner ashore in the harbour - a gentle start while the group finds its rhythm." },
      { day: 2, title: "Hydra", body: "The car-free island at its June best: mules, stone mansions, harbour swimming before the summer crowds build." },
      { day: 3, title: "Spetses", body: "Old-harbour elegance, pine shorelines, long swim stops on the way - June water is fully swimmable and the light lasts past nine." },
      { day: 4, title: "Ermioni · Dokos", body: "Quiet mainland-coast evening or a wild-anchorage night at Dokos - the kind of stop July timetables skip." },
      { day: 5, title: "Kythnos · Kolona", body: "Cross into the western Cyclades for the double-sided sandbar at Kolona - in June you may share it with nobody." },
      { day: 6, title: "Kea · Vourkari", body: "Quayside dinner at Vourkari; the Cycladic season is open but unhurried." },
      { day: 7, title: "Return to Athens", body: "Morning swim, gentle return leg, disembark with the whole summer still ahead." },
    ],
    whyGeorgeYachts: [
      "Priority 2027 access: tell George the week now and see the calendars as owners open them in autumn 2026.",
      "A curated crewed fleet he knows first-hand, matched to June's longer days and gentler winds.",
      "IYBA member, MYBA-standard contracts, Greek waters exclusively - and he answers personally.",
    ],
    faq: [
      { q: "When should I book a June 2027 charter?", a: "Autumn 2026 is the intelligent window. Owners publish 2027 rate cards then, and late-June weeks that align with US school holidays are among the first to go. Booking early buys choice of yacht and week, not a discount." },
      { q: "How warm is the sea in Greece in June?", a: "Comfortably swimmable and warming week by week - by late June the Aegean is in full summer mode. What June adds over August is daylight: the longest days of the year and calmer winds than the Meltemi peak." },
      { q: "Is June cheaper than July and August in Greece?", a: "Typically yes - June sits a step below the July-August peak on most rate cards, and it is also easier to negotiate on yachts with open calendars. Exact 2027 rates appear when owners publish their cards in autumn 2026." },
    ],
    seoTitle: "Yacht Charter Greece June 2027 | Book the Value Month",
    seoDescription: "June 2027 crewed yacht charter in Greece: longest days, warm sea, rates below peak. When to book, reference pricing, and a 7-day route. Priority access via George Yachts.",
  },

  {
    slug: "yacht-charter-greece-july-2027",
    urlPath: "/yacht-charter-greece-july-2027",
    eyebrow: "July 2027 · Peak Season",
    h1: "Yacht Charter in Greece, July 2027",
    tagline: "The heart of the Greek summer. The weeks everyone's school calendar points at - which is exactly why they are decided the previous autumn.",
    quickAnswerQ: "When should I book a July 2027 yacht charter in Greece?",
    quickAnswerA: "Autumn 2026, realistically. July is peak season: school holidays across Europe and the US meet the warmest weather, so the most requested crewed yachts see their July 2027 weeks spoken for months before summer. Owners publish 2027 rate cards in autumn 2026, and priority-listed clients see them first. Reference pricing (2026 Index): crewed catamarans roughly EUR 20,000-40,000 per week net in the Cyclades; motor yachts 24-34m EUR 35,000-100,000.",
    yachtRecs: [
      { kind: "Crewed sailing catamaran", cabins: "4-5 cabins", crew: "3-6 crew", weekly: "€20,000 - €40,000 (2026 ref., Cyclades)", fitFor: "Families - stability when the Meltemi works" },
      { kind: "Power catamaran", cabins: "4-6 cabins", crew: "3-5 crew", weekly: "€34,000 - €90,000 (2026 ref.)", fitFor: "More islands, less time under way" },
      { kind: "Motor yacht 24-34m", cabins: "4-6 cabins", crew: "5-8 crew", weekly: "€35,000 - €100,000 (2026 ref.)", fitFor: "The classic July family charter" },
    ],
    pricingNote: "2026 Charter Index reference bands; owners publish 2027 rate cards in autumn 2026. July is the month with the least negotiating room - the lever is booking early, not haggling late.",
    itinerary: [
      { day: 1, title: "Athens (Alimos) · Kea", body: "Afternoon boarding, evening crossing to Vourkari. July tip: the captain plans each leg around the Meltemi forecast - mornings move, afternoons swim." },
      { day: 2, title: "Kythnos · Kolona", body: "The sandbar anchorage at its postcard best. Water toys out all afternoon in the protected bay." },
      { day: 3, title: "Sifnos · Vathy", body: "The sheltered western bay with the white chapel at the waterline - a July favourite precisely because it hides from the wind." },
      { day: 4, title: "Polyaigos & Kimolos", body: "The clearest water in the Aegean, uninhabited coastline, lee-side swimming all day." },
      { day: 5, title: "Folegandros", body: "The near-vertical chora at dusk - book the tavernas ahead in July; your crew handles it." },
      { day: 6, title: "Ios · Manganari", body: "Protected southern crescent of sand - the family beach day of the week." },
      { day: 7, title: "Paros · Naoussa", body: "Final harbour evening in Naoussa, disembarkation the next morning." },
    ],
    whyGeorgeYachts: [
      "The July calendars are won in autumn: George's 2027 priority list puts you first in line when owners open their weeks.",
      "Captains who route around the Meltemi instead of fighting it - July comfort is a planning skill.",
      "A curated fleet he has walked himself, not a directory of listings.",
    ],
    faq: [
      { q: "How early do July charters in Greece sell out?", a: "The most loved crewed yachts see their late-July weeks committed months ahead - conversations start when owners publish 2027 rate cards in autumn 2026, and repeat clients call even earlier. If your dates are fixed by school holidays, autumn is when the choice is still full." },
      { q: "What about the Meltemi in July?", a: "July is the Meltemi's season, mostly over the open Cyclades. On a professionally crewed yacht it is a planning factor, not a danger: your captain reads the forecast days ahead and reshapes legs around it. Wind-averse groups can also charter the Ionian or Saronic, which sit largely outside its reach." },
      { q: "Is July or August better for a family charter in Greece?", a: "They are twins in weather and price; the difference is texture. July harbours build toward the August crescendo; early July is noticeably calmer than the first two weeks of August, which are the busiest of the Greek year. Either way, the booking calendar - not the weather - is what rewards deciding early." },
    ],
    seoTitle: "Yacht Charter Greece July 2027 | Book Peak Season Early",
    seoDescription: "July 2027 crewed yacht charter in Greece: the peak-season month, when to book it (autumn 2026), reference pricing, Meltemi-smart routing. Priority access via George Yachts.",
  },

  {
    slug: "yacht-charter-greece-august-2027",
    urlPath: "/yacht-charter-greece-august-2027",
    eyebrow: "August 2027 · The Family Peak",
    h1: "Yacht Charter in Greece, August 2027",
    tagline: "The Greek summer at full volume - and the weeks that vanish first from every owner's 2027 calendar.",
    quickAnswerQ: "Can I still get a good yacht for August 2027 in Greece, and when should I move?",
    quickAnswerA: "Yes - if you move in autumn 2026. August is the single most requested month on every Greek rate card: European holidays peak, families travel, and the best crewed yachts see August 2027 spoken for before spring. Owners publish 2027 rates in autumn 2026; priority-listed clients choose while the calendar is full. Reference pricing (2026 Index): crewed catamarans roughly EUR 20,000-40,000 per week net in the Cyclades; motor yachts 24-34m EUR 35,000-100,000; 35-49m EUR 100,000-350,000.",
    yachtRecs: [
      { kind: "Crewed sailing catamaran", cabins: "4-5 cabins", crew: "3-6 crew", weekly: "€20,000 - €40,000 (2026 ref., Cyclades)", fitFor: "The family default - stability and space" },
      { kind: "Motor yacht 24-34m", cabins: "4-6 cabins", crew: "5-8 crew", weekly: "€35,000 - €100,000 (2026 ref.)", fitFor: "Speed between anchorages at the busiest time" },
      { kind: "Motor yacht 35-49m", cabins: "5-6 cabins", crew: "8-10 crew", weekly: "€100,000 - €350,000 (2026 ref.)", fitFor: "Multi-family August celebrations" },
    ],
    pricingNote: "2026 Charter Index reference bands; owners publish 2027 rate cards in autumn 2026. August has effectively zero discounting - the early mover's advantage is the yacht itself.",
    itinerary: [
      { day: 1, title: "Athens (Alimos) · Poros", body: "Board and slip out of the city. August wisdom: the Saronic first night avoids the open-Aegean crossing on day one." },
      { day: 2, title: "Hydra (early) · Ermioni", body: "Hydra at breakfast, before the day-boats arrive - the crew times the marquee stops against the crowds." },
      { day: 3, title: "Spetses", body: "Old-harbour evening; lunch and swims in the pine coves on the way." },
      { day: 4, title: "Dokos · Kythnos", body: "Wild-anchorage swim stop, then the crossing to Kolona timed to the forecast." },
      { day: 5, title: "Serifos or Sifnos", body: "Lee-side bays chosen on the day - August rewards captains with options, and this coast is full of them." },
      { day: 6, title: "Polyaigos", body: "The Aegean's clearest water; in August its emptiness feels like a magic trick." },
      { day: 7, title: "Paros · Naoussa", body: "Naoussa finale - your crew has the dinner table that August walk-ins cannot get." },
    ],
    whyGeorgeYachts: [
      "August 2027 is decided in autumn 2026: the priority list exists precisely for these weeks.",
      "Crews and captains who work the crowd calendar - marquee harbours early, wild anchorages when the day-boats arrive.",
      "Straight answers: if a yacht or a week is wrong for August, George says so before you commit.",
    ],
    faq: [
      { q: "How far in advance should I book August 2027?", a: "Treat autumn 2026 as the deadline for first choice. The most requested crewed yachts see August spoken for months before summer, and the specific combination you want - the right yacht, the right week - is exactly what disappears first. Late deals exist in August, but the yacht you actually wanted is rarely among them." },
      { q: "Is Greece too crowded in August?", a: "The famous harbours are at full volume - that is half the fun and the whole point of a yacht: you visit the marquee stops on your own schedule and sleep in bays the crowds cannot reach. A good crew choreographs the week around the calendar: Hydra at breakfast, Polyaigos at noon, dinner tables pre-arranged." },
      { q: "August or September for 2027?", a: "If school terms bind you, August. If they do not, early September gives you the same warm sea with the crowds gone and more negotiating room - it is the month experienced charterers quietly prefer. Both reward early booking; August simply punishes lateness harder." },
    ],
    seoTitle: "Yacht Charter Greece August 2027 | The Weeks That Go First",
    seoDescription: "August 2027 crewed yacht charter in Greece: the most requested month, when to book (autumn 2026), reference pricing, crowd-smart routing. Priority access via George Yachts.",
  },

  {
    slug: "yacht-charter-greece-september-2027",
    urlPath: "/yacht-charter-greece-september-2027",
    eyebrow: "September 2027 · The Connoisseur's Month",
    h1: "Yacht Charter in Greece, September 2027",
    tagline: "The warmest sea of the year, the crowds gone, the Meltemi fading. The first September 2027 charter went to signatures in July 2026 - fourteen months out.",
    quickAnswerQ: "Why book September 2027 in Greece now, a year ahead?",
    quickAnswerA: "Because the people who know the Greek season best move first: the first September 2027 charter reached signatures in July 2026, fourteen months out. September is the connoisseur's month - the Aegean at its warmest after the long summer, the Meltemi fading, anchorages half empty, and adult company in every harbour. Owners publish 2027 rate cards in autumn 2026. Reference pricing (2026 Index): crewed catamarans roughly EUR 15,000-40,000 per week net; motor yachts 24-34m EUR 30,000-100,000.",
    yachtRecs: [
      { kind: "Crewed sailing catamaran", cabins: "4-5 cabins", crew: "3-6 crew", weekly: "€15,000 - €40,000 (2026 ref.)", fitFor: "Couples groups - flat decks, warm water" },
      { kind: "Crewed sailing monohull", cabins: "3-4 cabins", crew: "2-4 crew", weekly: "from €11,000 (2026 ref.)", fitFor: "September is Greece's finest sailing month" },
      { kind: "Motor yacht 24-34m", cabins: "4-6 cabins", crew: "5-8 crew", weekly: "€30,000 - €100,000 (2026 ref.)", fitFor: "The open-Cyclades route August makes difficult" },
    ],
    pricingNote: "2026 Charter Index reference bands; owners publish 2027 rate cards in autumn 2026. September is the one month where early conversations sometimes do find genuine rate flexibility.",
    itinerary: [
      { day: 1, title: "Athens (Alimos) · Kea", body: "The season's gentlest boarding: warm evening, empty quay at Vourkari, dinner steps from the tender." },
      { day: 2, title: "Kythnos · Kolona", body: "The sandbar to yourselves - September's signature experience is August's postcard without the fleet." },
      { day: 3, title: "Sifnos · Vathy", body: "The island's food scene at its unhurried best; the chapel bay flat as glass." },
      { day: 4, title: "Folegandros", body: "The chora at dusk with tables free - the fading Meltemi opens the whole southwest Cyclades." },
      { day: 5, title: "Ios · Manganari", body: "The warmest swimming of the entire year - the sea holds its accumulated summer heat into October." },
      { day: 6, title: "Paros · Antiparos channel", body: "Soros and the channel anchorages, then Naoussa without the queue." },
      { day: 7, title: "Return via Kea", body: "One last long lunch at anchor. Disembark rested, not relieved." },
    ],
    whyGeorgeYachts: [
      "George made the public case for September - and the market is catching up: the first September 2027 contract signed fourteen months early.",
      "Priority 2027 access: your brief waits at the front of the queue when owners open the calendars in autumn 2026.",
      "Honest brokerage: September's few real trade-offs (shorter days, late-month weather variance) are told to you before you book, not after.",
    ],
    faq: [
      { q: "Is September really better than August in Greece?", a: "For couples and adult groups, usually yes: the sea is warmer than June, the Meltemi fades through the month, anchorages empty out, and the islands stay fully open. The honest trade-offs are shorter days and a little more weather variance in the final week. Families tied to school terms keep August; nearly everyone else who tries September repeats it." },
      { q: "When should I book September 2027?", a: "The serious answer: now. The first September 2027 charter reached signatures in July 2026. Owners publish 2027 rate cards in autumn 2026, and September weeks on the most loved yachts are increasingly early-decided as more charterers discover the month. A no-commitment priority brief costs five minutes." },
      { q: "How warm is the sea in Greece in September?", a: "At or near its warmest of the entire year - the sea lags the air by weeks, so after the long Greek summer the Aegean enters September holding its accumulated heat and stays swimmable through the month and often well into October. If long swims are the point of the charter, September beats June comfortably." },
    ],
    seoTitle: "Yacht Charter Greece September 2027 | The Month Insiders Book First",
    seoDescription: "September 2027 crewed yacht charter in Greece: warmest sea, no crowds, fading winds - and the first 2027 contracts already signing. When and how to book via George Yachts.",
  },
];

export function getBottomFunnelPageBySlug(slug) {
  return BOTTOM_FUNNEL_PAGES.find((p) => p.slug === slug) || null;
}
