/**
 * The sample week, planned from the boat rather than written around her.
 *
 * ── The two mistakes this replaces ───────────────────────────────────────
 *
 * Sample itineraries used to be written per yacht and never checked against
 * the yacht. Measured on 8 September across the fifty-five hulls that had
 * one, both failures were live at once:
 *
 *   ABOVE AND BEYOND    10 knots, longest leg 95 NM   9.5 hours underway
 *   AD ASTRA            10 knots, longest leg 80 NM   8.0 hours
 *   HUAYRA               7 knots, longest leg 55 NM   7.9 hours
 *   SEA U               25 knots, longest leg 30 NM   1.2 hours
 *   M FIVE              23 knots, longest leg 30 NM   1.3 hours
 *   ONE                 33 knots, longest leg 65 NM   2.0 hours
 *
 * The first three are deliveries sold as charter days. The last three are
 * boats capable of the Cyclades before lunch being shown a week they would
 * finish by Wednesday. George's instruction on 8 September was the rule
 * itself: a yacht that runs at thirty knots does not belong in the Saronic,
 * a catamaran that runs at eight does not belong crossing to Mykonos, and
 * where the boat is based decides where the week can start.
 *
 * ── How a week is built now ──────────────────────────────────────────────
 *
 * 1. Read the boat: cruising speed, hull type, home port.
 * 2. Turn speed into a ceiling. A sailing boat will happily spend five
 *    hours under way, because the sailing is the point. A planing motor
 *    yacht will not: guests board her to be somewhere, and three and a half
 *    hours is the outside of a pleasant morning. So the day's reach is
 *    cruising speed times five for sail, times three and a half for power.
 * 3. Search the chart in lib/cruisingGrounds.js for the best seven-leg
 *    circuit that leaves the home port, never repeats a stop, keeps every
 *    single leg inside that ceiling, and comes home on a short final hop
 *    so nobody spends the last morning at sea.
 * 4. Among the circuits that qualify, take the one that visits the best
 *    islands. Better is a fixed number per port, not a guess per boat.
 *
 * The consequence is the rule George asked for, and it falls out of the
 * arithmetic rather than being imposed on top of it. A seven knot catamaran
 * has a thirty-five mile day and the Saronic is what fits inside it. A
 * twenty-five knot motor yacht has an eighty-seven mile day and Mykonos is
 * a morning away. Nobody has to remember to apply it.
 *
 * ── What is deliberately not here ────────────────────────────────────────
 *
 * No yacht is sent outside the operating grounds. The chart contains
 * Athens, the Saronic, the Cyclades and the Ionian and nothing else, so a
 * week in the Dodecanese cannot be generated by accident.
 */

import { PORTS, NETWORK, legDistance } from "./cruisingGrounds.js";

/** Hours under way a guest will accept, by what the boat is. */
const HOURS_CEILING = {
  // Four and a half hours for a sailing boat, because the sailing is the
  // point and a cat under way is where guests want to be. Not five: at five
  // a nine knot catamaran is handed a forty five mile crossing to Paros,
  // which is the same mistake as before in a smaller size.
  sail: 4.5,
  // Three and a half for anything with engines. Guests board a motor yacht
  // to be somewhere, not to be under way, and past three and a half hours
  // the day has been spent rather than used.
  power: 3.5,
};

/**
 * How short the last leg home should be, as a fraction of the ceiling.
 *
 * The boat is back at her berth the evening before guests step off, so this
 * is a full day and not a morning. It is still shorter than the ceiling,
 * because the last day should not be the hardest one, and it works out at
 * three hours for a motor yacht and a little over four for a sailing boat.
 */
const HOMECOMING = 0.85;

/**
 * And how short the first one. Guests board in the late afternoon, so the
 * first evening is a hop to somewhere with dinner ashore, never a passage.
 * Two and a half hours under way is the outside of it, and it is counted in
 * hours rather than as a share of the day's reach: on the fraction the cap
 * moved with the boat and a sixteen knot catamaran was refused the two hour
 * run to Kea that every real charter out of Alimos makes on the first
 * evening. Hours are what the guests feel.
 */
const FIRST_LEG_HOURS = 2.5;

/**
 * What a circuit earns for using the boat she is.
 *
 * Without this the search hands a sixteen knot power catamaran the same
 * Saronic week as a seven knot sailing cat, because Hydra and Spetses score
 * higher than Kythnos and Serifos and both weeks are legal. That is exactly
 * the mistake George named: the power is in the boat and the week never
 * shows it. So a circuit also earns for the water it covers, measured
 * against what the boat could cover, and a fast hull is pushed out to the
 * islands only a fast hull reaches. Twelve points is worth more than
 * trading Hydra for Kythnos and less than trading away half a week.
 */
const USE_HER = 12;

/**
 * How much a stop is worth to a charter guest. Not a rating of the island,
 * a rating of the day it makes: an anchorage nobody can reach by ferry
 * scores above a town everybody can.
 */
const DRAW = {
  // Saronic and Argolic
  aegina: 6, aeginatown: 5, agkistri: 4, epidaurus: 6, poros: 7,
  hydra: 10, dokos: 5, ermioni: 5, spetses: 9, porto_heli: 6, nafplio: 7,
  // Cyclades
  kea: 6, kythnos: 7, serifos: 6, sifnos: 8, milos: 9, kimolos: 5,
  folegandros: 7, santorini: 10, ios: 7, paros: 8, antiparos: 6,
  naxos: 7, koufonisia: 8, amorgos: 7, mykonos: 10, delos: 9, rinia: 5,
  syros: 7, tinos: 6, andros: 5, schinoussa: 5,
  // Ionian
  lefkada: 3, preveza: 3, gouvia: 7, zakynthos: 7, sivota_lef: 6,
  meganisi: 7, kalamos: 5, kastos: 5, ithaca: 8, vathy_ith: 6,
  fiskardo: 9, sami: 5, argostoli: 6, poros_kef: 5, paxos: 9,
  antipaxos: 8, sivota_mai: 6, parga: 6, atokos: 7, petalas: 3,
  // the delivery ports score nothing as destinations
  alimos: 0, flisvos: 0, zea: 0, lavrio: 0, neaperamos: 0,
  // Sounion is a real stop, not a delivery port: the temple stands over
  // the anchorage and the sunset from it is the reason boats stay.
  sounion: 7,
};

/** Sail or power, which decides the hours a guest will sit still for. */
export function propulsionOf(category) {
  return category === "sailing-catamarans" || category === "sailing-monohulls"
    ? "sail"
    : "power";
}

/**
 * Read a cruising speed out of whatever the Studio holds. The field is free
 * text and has held "22 knots", "9 to 10 knots", "7-9 knots" and "21.5
 * knots". A range resolves to its lower figure, because the week has to
 * work on the slow day as well as the fast one.
 */
export function cruisingKnots(raw) {
  if (typeof raw === "number" && raw > 0) return raw;
  if (!raw) return null;
  const nums = String(raw).match(/\d+(?:\.\d+)?/g);
  if (!nums || !nums.length) return null;
  return Math.min(...nums.map(Number));
}

/** The furthest a boat should be asked to go in one day. */
export function dayReach(knots, propulsion) {
  if (!knots) return null;
  return Math.round(knots * HOURS_CEILING[propulsion]);
}

/**
 * Every seven-leg circuit from a base, best first.
 *
 * Beam search rather than exhaustive: the chart has fifty-seven ports and
 * the number of seven-leg walks runs to millions, most of them the same
 * week with two islands swapped. A beam of a few hundred partial routes,
 * kept ordered by the islands they have reached so far, finds the good
 * ones and finishes in milliseconds.
 */
function bestCircuit(base, maxLeg, knots, legs = 7, beamWidth = 400) {
  if (!NETWORK[base]) return null;
  const firstLegMax = Math.min(maxLeg, knots * FIRST_LEG_HOURS);

  let beam = [{ path: [base], nm: [], total: 0, draw: 0 }];

  for (let step = 0; step < legs; step++) {
    const last = step === legs - 1;
    const next = [];

    for (const state of beam) {
      const here = state.path[state.path.length - 1];
      for (const leg of NETWORK[here]) {
        if (leg.nm > maxLeg) continue;
        if (step === 0 && leg.nm > firstLegMax) continue;
        if (last) {
          // The final leg has to land on the base, and it has to be short
          // enough that the last morning is a swim rather than a passage.
          if (leg.to !== base) continue;
          if (leg.nm > maxLeg * HOMECOMING) continue;
        } else {
          if (state.path.includes(leg.to)) continue;
          // No Athens berth appears in the middle of a week. Without this
          // ALEGRIA's Saronic week came back into Flisvos on day four and
          // left again on day five, which is a repositioning run, not a
          // charter day, and it reads to a guest as a mistake. The five
          // Attic marinas are one city and interchangeable; the Ionian
          // harbours are forty miles apart and are real stops, so they are
          // not marked this way and a week can call at them.
          if (PORTS[leg.to].delivery) continue;
        }
        next.push({
          path: [...state.path, leg.to],
          nm: [...state.nm, leg.nm],
          notes: [...(state.notes || []), leg.note || null],
          total: state.total + leg.nm,
          draw: state.draw + (DRAW[leg.to] ?? 4),
        });
      }
    }

    if (!next.length) return null;

    // Rank by the islands reached plus the water covered, so two legal
    // weeks are separated by the one that actually uses the hull.
    const score = (s) => s.draw + (USE_HER * s.total) / (legs * maxLeg);
    next.sort((a, b) => score(b) - score(a) || b.total - a.total);

    // Keep the beam varied: at most a handful of partial routes ending at
    // the same port, or every slot fills with minor variants of one week.
    const perTail = {};
    beam = [];
    for (const s of next) {
      const tail = s.path[s.path.length - 1];
      perTail[tail] = (perTail[tail] || 0) + 1;
      if (perTail[tail] > 6) continue;
      beam.push(s);
      if (beam.length >= beamWidth) break;
    }
  }

  return beam;
}

/**
 * A stable number from a slug, so a yacht is handed the same week every
 * time the site builds. Nothing random reaches a page: two deploys an hour
 * apart must not quietly rewrite forty itineraries, because every rewrite
 * is a changed page and the crawl budget is still recovering from August.
 */
function seedOf(slug) {
  let h = 2166136261;
  for (let i = 0; i < slug.length; i++) {
    h ^= slug.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
}

/**
 * Plan a week.
 *
 * Returns null rather than guessing when the boat has no recorded cruising
 * speed or when no circuit fits her. A missing itinerary is a gap somebody
 * can fill; an invented one is a promise the boat cannot keep.
 */
export function planWeek({ base, cruiseSpeed, category, slug = "", days = 7 }) {
  const knots = cruisingKnots(cruiseSpeed);
  if (!knots || !PORTS[base]) return null;

  const propulsion = propulsionOf(category);
  const reach = dayReach(knots, propulsion);

  // Try the full reach first, then tighten. A boat that can run eighty
  // miles does not have to, and a shorter ceiling often finds a better
  // week: the search is free, so take the best of several.
  let attempts = [];
  for (const factor of [1, 0.85, 0.7, 0.55]) {
    attempts = attempts.concat(
      bestCircuit(base, Math.round(reach * factor), knots, days) || [],
    );
  }
  if (!attempts.length) return null;

  const score = (s) => s.draw + (USE_HER * s.total) / (days * reach);
  attempts.sort((a, b) => score(b) - score(a) || b.total - a.total);

  // ── Why the best week is not simply handed to every boat ──────────────
  //
  // Sixteen power catamarans in this fleet cruise between eleven and
  // sixteen knots out of the same marina. Handing each of them the highest
  // scoring circuit would put the identical seven days on sixteen pages,
  // which is duplicate copy on the one section of a yacht page a guest
  // reads closely, and thin repetition on the one section a language model
  // quotes. So the search keeps every circuit that comes within a tenth of
  // the best, drops the ones that call at the same islands, and each yacht
  // takes hers by name. The same boat gets the same week on every build,
  // which matters more than it sounds: a route that shuffled between
  // deploys would restamp forty pages and send the crawler round the fleet
  // again for nothing.
  // The ground is decided once, by the best circuit the boat can sail, and
  // every alternative has to stay in it. Without that clause a twenty-three
  // knot motor yacht could be handed a Saronic week because it happened to
  // score within a tenth of her Cyclades one, which is the exact mistake
  // this file exists to end. M FIVE picked up precisely that week in
  // testing before the clause went in.
  const homeGround = PORTS[base].ground;
  const groundOf = (c) => {
    const tally = {};
    for (const port of c.path.slice(1, -1)) {
      const g = PORTS[port].ground;
      // A stop on the way out of the home ground does not decide where the
      // week is. Sounion is on the Attic coast and half the Cyclades weeks
      // in this fleet start with a night under the temple; counting it would
      // file those weeks under Athens and let a Saronic circuit pass as an
      // alternative to a Cyclades one.
      if (g === homeGround) continue;
      tally[g] = (tally[g] || 0) + 1;
    }
    const ranked = Object.entries(tally).sort((a, b) => b[1] - a[1]);
    return ranked.length ? ranked[0][0] : homeGround;
  };
  const ground = groundOf(attempts[0]);
  const best = score(attempts[0]);

  const shortlist = [];
  const seen = new Set();
  for (const a of attempts) {
    if (score(a) < best * 0.8) break;
    if (groundOf(a) !== ground) continue;
    const signature = a.path.slice(1, -1).sort().join("|");
    if (seen.has(signature)) continue;
    seen.add(signature);
    shortlist.push(a);
    if (shortlist.length >= 14) break;
  }
  const circuit = shortlist[seedOf(slug || base) % shortlist.length];

  return {
    base,
    knots,
    propulsion,
    reach,
    ports: circuit.path,
    variants: shortlist.length,
    legs: circuit.nm,
    notes: circuit.notes,
    total: circuit.total,
    hoursLongest: Math.round((Math.max(...circuit.nm) / knots) * 10) / 10,
  };
}
