// Bridge auto-cron menu button handler — Update 3 §1.
//
// This endpoint is the URL target for every menu button generated by
// the Thursday cron. George taps a Telegram URL button → his browser
// loads this endpoint → we verify the HMAC token + idempotency, then:
//
//   action=blog   → call /api/admin/newsletter-compose to make a
//                   /blog draft for the picked post slug; the standard
//                   approval card flow takes over from there
//   action=yacht  → same, but content_type=announcement + the picked
//                   yacht slug; on successful approval+send, the
//                   yacht is added to featured_yachts:bridge
//   action=skip   → record that this week was skipped, no draft
//
// HMAC binds (action, fire_id, slug) so a token from one button can
// never be replayed for another. Once any button on this fire_id is
// tapped, auto_bridge_processed:<fire_id> is set so subsequent taps
// gracefully no-op with a status page.

import { NextResponse } from "next/server";
import {
  verifyAutoBridgePickToken,
  sendTelegramText,
} from "@/lib/newsletter/telegram";
import {
  getProcessedAction,
  markProcessed,
  markYachtAsFeatured,
} from "@/lib/newsletter/auto-bridge";

export const dynamic = "force-dynamic";
export const runtime = "nodejs";

function htmlPage(title, body) {
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/><title>${title} — George Yachts</title>
<style>
  body { font-family: Georgia, "Times New Roman", serif; background:#F8F5F0; color:#0D1B2A; margin:0; padding:48px 24px; }
  .card { max-width: 520px; margin: 0 auto; background: #fff; padding: 36px; border: 1px solid #E5DFD3; }
  h1 { font-family: 'Cormorant Garamond', Georgia, serif; font-weight: 300; letter-spacing: 0.04em; font-size: 28px; margin: 0 0 8px 0; }
  .gold { color: #C9A84C; font-size: 11px; text-transform: uppercase; letter-spacing: 0.32em; margin-bottom: 24px; }
  p { line-height: 1.65; }
  code { background:#f0ece2; padding:2px 6px; }
</style></head>
<body><div class="card"><div class="gold">Bridge auto-cron</div><h1>${title}</h1>${body}</div></body></html>`;
}

export async function GET(request) {
  const url = new URL(request.url);
  const action = url.searchParams.get("action") || "";
  const fireId = url.searchParams.get("fire_id") || "";
  const slug = url.searchParams.get("slug") || "";
  const token = url.searchParams.get("token") || "";

  // Token verification first — any failure here is silent and final.
  const ok = verifyAutoBridgePickToken({ action, fire_id: fireId, slug, token });
  if (!ok) {
    return new NextResponse(
      htmlPage(
        "Token invalid or expired",
        `<p>This Bridge menu button could not be verified. The cron generates a fresh menu every Thursday — wait for the next one, or trigger manually from the admin endpoint.</p>`,
      ),
      { status: 401, headers: { "Content-Type": "text/html; charset=utf-8" } },
    );
  }

  // Idempotency — once any button on this fire_id is processed, the
  // menu is "spent". Subsequent taps return a graceful status page.
  const already = await getProcessedAction(fireId);
  if (already) {
    return new NextResponse(
      htmlPage(
        "Already handled",
        `<p>This week's Bridge menu was already processed (action: <code>${already}</code>). The next auto-cron menu fires next Thursday at 06:00 UTC.</p>`,
      ),
      { status: 200, headers: { "Content-Type": "text/html; charset=utf-8" } },
    );
  }

  // Dispatch.
  if (action === "skip") {
    await markProcessed(fireId, "skip");
    await sendTelegramText(
      `⏸ <b>Bridge skipped this week</b>\nFire ID: <code>${fireId}</code>\nNext auto-fire: next Thursday 06:00 UTC.`,
    ).catch(() => {});
    return new NextResponse(
      htmlPage(
        "Skipped",
        `<p>This week's Bridge auto-fire is paused. The cron will check again next Thursday at 06:00 UTC.</p>`,
      ),
      { status: 200, headers: { "Content-Type": "text/html; charset=utf-8" } },
    );
  }

  if (action !== "blog" && action !== "yacht") {
    return new NextResponse(
      htmlPage("Unknown action", `<p>Unknown menu action: <code>${action}</code>.</p>`),
      { status: 400, headers: { "Content-Type": "text/html; charset=utf-8" } },
    );
  }

  // For blog + yacht we delegate to the existing compose endpoint
  // (Phase 3) which handles the assembly, validator, KV draft write,
  // and Telegram approval card. Internal HTTP call so we don't
  // refactor the compose route — single source of truth preserved.
  const proxySecret =
    process.env.NEWSLETTER_PROXY_SECRET ||
    process.env.NEWSLETTER_UNSUB_SECRET ||
    process.env.CRON_SECRET;
  if (!proxySecret) {
    return new NextResponse(
      htmlPage(
        "Server misconfigured",
        `<p>NEWSLETTER_PROXY_SECRET / NEWSLETTER_UNSUB_SECRET not set on this deploy. Cannot internally call the compose endpoint.</p>`,
      ),
      { status: 500, headers: { "Content-Type": "text/html; charset=utf-8" } },
    );
  }
  const base = process.env.NEXT_PUBLIC_SITE_URL || "https://georgeyachts.com";
  const composeUrl = `${base}/api/admin/newsletter-compose?key=${encodeURIComponent(proxySecret)}`;

  const payload =
    action === "blog"
      ? {
          content_type: "blog",
          audience: ["bridge"],
          post_slug: slug,
          // No george_angle — the cron path doesn't have a per-issue
          // angle from George. He'll see the assembled body in the
          // approval card and can ❌ Abort + redo via Composer if the
          // tone needs an angle.
        }
      : {
          content_type: "announcement",
          audience: ["bridge"],
          yacht_slug: slug,
        };

  let composeRes;
  try {
    const r = await fetch(composeUrl, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(payload),
      cache: "no-store",
    });
    composeRes = await r.json();
  } catch (err) {
    await sendTelegramText(
      `🚨 <b>Bridge auto-cron: compose call failed</b>\n` +
        `Action: ${action}\nSlug: ${slug}\nFire ID: ${fireId}\n\nError: ${err?.message || err}`,
    ).catch(() => {});
    return new NextResponse(
      htmlPage(
        "Compose failed",
        `<p>Could not reach the compose endpoint. Telegram alert sent. Try the manual Composer in the CRM.</p>`,
      ),
      { status: 500, headers: { "Content-Type": "text/html; charset=utf-8" } },
    );
  }

  // Mark processed BEFORE returning so the user can't double-tap and
  // create two drafts even if they refresh quickly.
  await markProcessed(fireId, action);

  // For yacht: capture the Sanity yacht _id from the compose result so
  // we can mark it featured AFTER George approves and sends. We don't
  // mark featured here — only on successful send. So we stash the _id
  // alongside the draft in KV and the /approve handler will pick it up
  // on send completion. (Implemented in /approve when phase 4 finalises;
  // for now we mark optimistically — yacht highlight is meant to be
  // one-shot per yacht regardless of George's approve/abort decision.)
  //
  // 2026-04-29 design call: optimistic mark. If George aborts the draft,
  // the yacht is still in featured_yachts:bridge — that's intentional.
  // The cron's job was to surface it; the yacht has had its turn in
  // the menu rotation. Re-adding it would mean re-prompting endlessly.
  if (action === "yacht" && composeRes?.results?.[0]?.draft_id) {
    // Look up the yacht by slug to get its _id. Sanity yacht slugs are
    // unique. We make a tiny additional fetch — acceptable cost for
    // the once-a-week cron path.
    try {
      const { sanityClient } = await import("@/lib/sanity");
      const y = await sanityClient.fetch(
        `*[_type == "yacht" && slug.current == $slug][0]{ _id }`,
        { slug },
      );
      if (y?._id) await markYachtAsFeatured(y._id);
    } catch {
      // best-effort
    }
  }

  // Surface the result. The compose endpoint already sent its own
  // approval card; we just acknowledge here.
  const tone =
    action === "blog"
      ? "📰 Blog recap drafted"
      : "⛵ Yacht highlight drafted";
  return new NextResponse(
    htmlPage(
      tone,
      `<p>Draft created for stream <code>bridge</code>. Open Telegram — the standard approval card with 👀 Preview / ✅ Approve / ❌ Abort buttons should be waiting. Nothing was sent yet.</p>` +
        `<p><small>Fire ID: <code>${fireId}</code></small></p>`,
    ),
    { status: 200, headers: { "Content-Type": "text/html; charset=utf-8" } },
  );
}
